/**
 * Tenvo Electronics demo / registration catalog.
 * Built from Telemart Shopify collections + archive/electronics.html + supplements.
 * Regenerate: node scripts/fetch-telemart-electronics-catalog.mjs && node scripts/build-electronics-seed-catalog.mjs
 */

/** @type {string[]} */
export const ELECTRONICS_SEED_CATEGORIES = [
  'Air Conditioners',
  'Refrigerators',
  'LED TVs',
  'Washing Machines',
  'Deep Freezers',
  'Kitchen Appliances',
  'Water Dispensers',
  'Cooling & Fans',
  'Gadgets & Wearables',
  'Small Appliances',
];

/** @type {Array<Record<string, unknown>>} */
export const ELECTRONICS_SEED_PRODUCTS = [
  {
    "name": "Kenwood KRF-26657 VCM Classic Plus Series Refrigerator 18 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 103999,
    "compare_price": 115000,
    "cost_price": 85279,
    "stock": 8,
    "sku": "TM-KENWOOD-KRF-26657-VCM-CLASSIC-PLUS-SERIES-REFRIG",
    "description": "Energy saving: Up to 35% energy efficiency. Low voltage startup to 170V. Ultraviolet Light: makes your food fresh. LED light: refrigerator and freezer. Insulation thickness up to 75 mm. Dry Vegetable tray. Antifungal detachable gas kit. Medical box. Cooling bank. Carbon filter. C",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_sJPeTGkxNXGZs2aJh4FKMveqUEChPqg39oQKq1XE.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 26657 vcm classic plus series refrigerator 18 cuft with official war",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "18 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-25557 VCM Classic Series Refrigerator 15 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 94999,
    "compare_price": 105000,
    "cost_price": 77899,
    "stock": 9,
    "sku": "TM-KENWOOD-KRF-25557-VCM-CLASSIC-SERIES-REFRIGERATO",
    "description": "Energy saving: Up to 35% energy efficiency. Low voltage startup to 170V. Ultraviolet Light: makes your food fresh. LED light: refrigerator and freezer. Insulation thickness up to 75 mm. Energy saving: Up to 35% energy efficiency. Low voltage startup to 170V. Ultraviolet Light: ma",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_I1WjGbKk9qcSLwSVOfHxZdpoZizQn5P4ld2MX9yJ.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 25557 vcm classic series refrigerator 15 cuft with official warranty",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "15 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-23357 VCM Classic Plus Series Refrigerator 11 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 84599,
    "compare_price": 95000,
    "cost_price": 69371,
    "stock": 10,
    "sku": "TM-KENWOOD-KRF-23357-VCM-CLASSIC-PLUS-SERIES-REFRIG",
    "description": "SECOP (German technology super quiet compressor) Vegetable tray with up to 10kg dry vegetable storage Can operate at voltage as low as 170V without tripping Easily removable/washable compressor drain tray The true capacity volume of refrigerator and freezer Embossed PCM sheet for",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_xMa9hZH81KEbxc9XCKHjyrEEGkC6VVyaPejqKv5k.png",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 23357 vcm classic plus series refrigerator 11 cuft with official war",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "11 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-24457 VCM Classic Plus Series Refrigerator 13 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 82999,
    "compare_price": 92000,
    "cost_price": 68059,
    "stock": 11,
    "sku": "TM-KENWOOD-KRF-24457-VCM-CLASSIC-PLUS-SERIES-REFRIG",
    "description": "13 CFT 1 Year Parts 12 Year Compresser Warranty SECOP (German technology super quiet compressor) Vegetable tray with up to 10kg dry vegetable storage Can operate at voltage as low as 170V without tripping Easily removable/washable compressor drain tray The true capacity volume of",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_9WHggsNfGI3Qopm8z3oroQ4eJlmMZLOVwwn7T34j.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 24457 vcm classic plus series refrigerator 13 cuft with official war",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "13 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-22257 VCM Classic Plus Refrigerator With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 65999,
    "compare_price": 75000,
    "cost_price": 54119,
    "stock": 12,
    "sku": "TM-KENWOOD-KRF-22257-VCM-CLASSIC-PLUS-REFRIGERATOR-",
    "description": "Brand : Kenwood Model : Kenwood Refrigerator KRF-22257 (VCM) (PBG) Classic Plus (220) Capacity : 220 Liters (approximately 9 cubic feet) Compressor Type : SECOP (German technology, super quiet) Voltage Operation : Operates at voltages as low as 170V without tripping Compressor Dr",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_HRnrCgqodvtv9pWuDSOcItYzWwUx9LiU93DjAkSY.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 22257 vcm classic plus refrigerator with official warranty",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-26657 GD 18 Cuft Refrigerator With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 104999,
    "compare_price": 115000,
    "cost_price": 86099,
    "stock": 13,
    "sku": "TM-KENWOOD-KRF-26657-GD-18-CUFT-REFRIGERATOR-WITH-O",
    "description": "Energy saving: Up to 35% energy efficiency. Low voltage startup to 170V. Ultraviolet Light: makes your food fresh. LED light: refrigerator and freezer. Insulation thickness up to 75 mm. Dry Vegetable tray. Antifungal detachable gas kit. Medical box. Cooling bank. Carbon filter. C",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_lsJ434gjOeXENCRJyS21MdqeiUukmv7DF5evy3DA.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 26657 gd 18 cuft refrigerator with official warranty",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "18 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-25557 GD Persona Plus Series Refrigerator 15 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 107999,
    "compare_price": 115000,
    "cost_price": 88559,
    "stock": 14,
    "sku": "TM-KENWOOD-KRF-25557-GD-PERSONA-PLUS-SERIES-REFRIGE",
    "description": "SECOP (German technology super quiet compressor) Vegetable tray with up to 10kg dry vegetable storage Can operate at voltage as low as 170V without tripping Easily removable/washable compressor drain tray True capacity volume of refrigerator and freezer Embossed PCM sheet for cab",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_cXV6pcUL4ZcvZAEBmcF8a63PkUiBJcRlAB5TQg1e.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 25557 gd persona plus series refrigerator 15 cuft with official warr",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "15 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KRF-24457 GD Persona Series Refrigerator 13 Cuft With Official Warranty",
    "brand": "Kenwood",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 97999,
    "compare_price": 105000,
    "cost_price": 80359,
    "stock": 15,
    "sku": "TM-KENWOOD-KRF-24457-GD-PERSONA-SERIES-REFRIGERATOR",
    "description": "SECOP (German technology super quiet compressor) Vegetable tray with up to 10kg dry vegetable storage Can operate at voltage as low as 170V without tripping Easily removable/washable compressor drain tray True capacity volume of refrigerator and freezer Embossed PCM sheet for cab",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_miq9neBRRMgWSbCsit95lko8ZlvcCUGfleZNTXjU.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood krf 24457 gd persona series refrigerator 13 cuft with official warranty",
      "warranty": "1 Year",
      "specifications": "Refrigerator",
      "capacity": "13 cu ft",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Dawlance DW-10500 Advanco 10Kg Top Load Twin Tub Semi Automatic Washing Machine with Official Warranty",
    "brand": "Dawlance",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 52499,
    "compare_price": 60000,
    "cost_price": 43049,
    "stock": 10,
    "sku": "TM-DAWLANCE-DW-10500-ADVANCO-10KG-TOP-LOAD-TWIN-TUB",
    "description": "Energy Information Voltage (V) 220 Frequency (Hz) 50 Dimensions & Weight Width (cm) 94 cm Depth (cm) 55.5 cm Height (cm) 105.5 cm Width (in) 37.007874 Depth (in) 21.850393 Height (in) 41.535435 Set Weight (kg) 32 kg Features Deep Waterfall Yes Shower Rinse Yes Spinner Yes Wide Im",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_mMOvkfDXYXwLE2K1Vs7Xg79c7BmK17o3k9iwmHzb.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "dawlance dw 10500 advanco 10kg top load twin tub semi automatic washing machine ",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "10 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Kenwood KWM-899W 8Kg Top Load Single Tub Washing Machine With Official Warranty",
    "brand": "Kenwood",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 26999,
    "compare_price": 32000,
    "cost_price": 22139,
    "stock": 11,
    "sku": "TM-KENWOOD-KWM-899W-8KG-TOP-LOAD-SINGLE-TUB-WASHING",
    "description": "Kenwood KSW- 899 8kg Washing Machine is designed to deliver reliable and efficient laundry care for everyday use. Its 8 kg capacity makes it suitable for small to medium households. With powerful washing performance and a durable body, it effectively removes dirt while protecting",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_SnTh7zHpkGazxTXqa2TdJt9ncFrhtWbJtEVVz4ns.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Kenwood",
      "model": "kenwood kwm 899w 8kg top load single tub washing machine with official warranty",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "8 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia ECM-4600 Plus Room Air Cooler with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 40799,
    "compare_price": 50000,
    "cost_price": 33455,
    "stock": 12,
    "sku": "TM-SUPER-ASIA-ECM-4600-PLUS-ROOM-AIR-COOLER-WITH-OF",
    "description": "Power Only 220 Volts Brand Warranty 2 Speed Control With Ice Box New Model 2022 Advance Technology Moveable Grill Tank Capacity 50 Litre 4 Way Mobility Auto Swing Turbo Fan Technology System Restore Function Strong outer Body (Shock Rust Proof Plastic Body) Continuous Water Suppl",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_WHOQcuHWBXSEXLwkgxzI42z6609SoZQOiwL9lfLN.png",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia ecm 4600 plus room air cooler with official warranty",
      "warranty": "1 Year",
      "specifications": "Room Cooler",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia SAP-320 Wash Thrill 7kg Single Tub Washing Machine with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 44299,
    "compare_price": 55000,
    "cost_price": 36325,
    "stock": 13,
    "sku": "TM-SUPER-ASIA-SAP-320-WASH-THRILL-7KG-SINGLE-TUB-WA",
    "description": "Rust proof painted metal body Steel drum with double storm pulsator Buzzer sounds (end of wash cycle) Powerful motor Energy saver",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_xoHLJejPQGq71m6mQ4wChq89GwzGsAskqzjvviAM.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia sap 320 wash thrill 7kg single tub washing machine with official warr",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "7 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia SD-525 Quick Spin 5kg Spin Dryer with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 24799,
    "compare_price": 30000,
    "cost_price": 20335,
    "stock": 14,
    "sku": "TM-SUPER-ASIA-SD-525-QUICK-SPIN-5KG-SPIN-DRYER-WITH",
    "description": "Model Number: SD-525 Product Type: Spin Dryer Series: Quick Spin Spinning Capacity: 5 kg Machine Type: Semi-Automatic Spinner Body Material: Shock & Rust-Proof Double Plastic Body Motor: Powerful Copper Motor Wash Tray: Easy Wash Tray Spin Technology: Shower Spin Technology Air D",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_3pKVWlCbxX5Ar8vn7sLCrBCOtG5YSNlhBNdNHLgH.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia sd 525 quick spin 5kg spin dryer with official warranty",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "5 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia SD-550 Easy Spin 10kg Spin Dryer with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 26099,
    "compare_price": 32000,
    "cost_price": 21401,
    "stock": 15,
    "sku": "TM-SUPER-ASIA-SD-550-EASY-SPIN-10KG-SPIN-DRYER-WITH",
    "description": "Shock & rust proof plastic body Quick spinning Shower spin technology Auto water balancing ring Power full motor Auto brake system Energy saver",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_9DPGrnd0LpiETJamgrJpVGgH4DgDHvmbMf9N7XlZ.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia sd 550 easy spin 10kg spin dryer with official warranty",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "10 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia SA-210 Quick Wash 4kg Single Tub Top Load Washing Machine with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 19499,
    "compare_price": 25000,
    "cost_price": 15989,
    "stock": 16,
    "sku": "TM-SUPER-ASIA-SA-210-QUICK-WASH-4KG-SINGLE-TUB-TOP-",
    "description": "Washing Capacity: 4 kg Shock & rust proof plastic body Scrub board with double storm pulsator Buzzer sounds (end of wash cycle) Powerful motor Energy saver Product Dimensions: 400 x 360 x 500",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_Gq9hLh7SKUyVD4gHeaUIvNNS3vy0tiX78feIMxgi.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia sa 210 quick wash 4kg single tub top load washing machine with offici",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "4 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia SA-110 Baby Wash 1Kg Top Load Washing Machine with Official Warranty",
    "brand": "Super Asia",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 14399,
    "compare_price": 18500,
    "cost_price": 11807,
    "stock": 17,
    "sku": "TM-SUPER-ASIA-SA-110-BABY-WASH-1KG-TOP-LOAD-WASHING",
    "description": "Washing Capacity: 1 kg Shock & rust proof plastic body Scrub board with double storm pulsator Buzzer sounds (end of wash cycle) Powerful motor Energy saver",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_JSRkE21MJ12wGGsS6zSSnXjRlUYN4adM8jUhGGlT.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia sa 110 baby wash 1kg top load washing machine with official warranty",
      "warranty": "1 Year",
      "specifications": "Washing Machine",
      "capacity": "1 KG",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Haier H98S90EUX 98 Inch 4K QLED Google TV With Official Warranty",
    "brand": "Haier",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 786999,
    "compare_price": 11005000,
    "cost_price": 645339,
    "stock": 12,
    "sku": "TM-HAIER-H98S90EUX-98-INCH-4K-QLED-GOOGLE-TV-WITH-O",
    "description": "Model Number: H98S90EUX Screen Size: 98 Inches Display Type: QLED (Quantum Dot) Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 120Hz Aspect Ratio: 16:9 Brightness: 450 nits Contrast Ratio: 6000:1 Viewing Angle: 178° / 178° Response Time: 6.5 ms Color Depth: 1.07 Billion Colors HD",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_7CPDlgE8QGwiMyl1kSPB9MZ972ZZpd41Ho02zApS.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Haier",
      "model": "haier h98s90eux 98 inch 4k qled google tv with official warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "98\"",
      "screensize": "98\"",
      "energylabel": ""
    }
  },
  {
    "name": "EcoStar Q965 4K QLED Google TV With Official Warranty",
    "brand": "EcoStar",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 295999,
    "compare_price": 310000,
    "cost_price": 242719,
    "stock": 13,
    "sku": "TM-ECOSTAR-Q965-4K-QLED-GOOGLE-TV-WITH-OFFICIAL-WAR",
    "description": "Series: Q965 Display Type: QLED (Quantum Dot) Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 60Hz HDR Support: HDR10 MEMC: Yes Picture Enhancement: AI Opti Color Processor: Cortex-A55 Quad-Core Operating System: Google TV Google Assistant: Built-in Chromecast Built-in: Yes RAM: 2",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_jtrAI9wQSs9Axik44Z66A72uIdOCndMQzey7sEYG.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "EcoStar",
      "model": "ecostar q965 4k qled google tv with official warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "EcoStar Q873 QLED Google TV With Official Warranty",
    "brand": "EcoStar",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 48499,
    "compare_price": 52379,
    "cost_price": 39769,
    "stock": 14,
    "sku": "TM-ECOSTAR-Q873-QLED-GOOGLE-TV-WITH-OFFICIAL-WARRAN",
    "description": "Series: Q873 Display Type: QLED Resolution: Full HD (1920 × 1080) Refresh Rate: 60Hz HDR Support: HDR Processor: Cortex-A55 Quad-Core Operating System: Google TV Google Assistant: Built-in Chromecast Built-in: Yes RAM: 1.5GB Storage (ROM): 8GB Dolby Audio: Yes Digital TV Tuner (D",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/1111_33.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "EcoStar",
      "model": "ecostar q873 qled google tv with official warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "EcoStar Q964 4K QLED Google TV With Official Warranty",
    "brand": "EcoStar",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 97999,
    "compare_price": 215000,
    "cost_price": 80359,
    "stock": 15,
    "sku": "TM-ECOSTAR-Q964-4K-QLED-GOOGLE-TV-WITH-OFFICIAL-WAR",
    "description": "Series: Q964 Display Type: QLED Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 60Hz HDR Support: HDR10 MEMC: Yes Picture Enhancement: AI Opti Color Processor: Cortex-A53 Quad-Core Operating System: Google TV Google Assistant: Built-in Chromecast Built-in: Yes RAM: 2GB Storage (RO",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/1111_32.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "EcoStar",
      "model": "ecostar q964 4k qled google tv with official warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "TCL S51K FHD Google TV With Official Warranty",
    "brand": "TCL",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 51999,
    "compare_price": 105000,
    "cost_price": 42639,
    "stock": 16,
    "sku": "TM-TCL-S51K-FHD-GOOGLE-TV-WITH-OFFICIAL-WARRANTY",
    "description": "Series: S51K Display Type: LED Resolution: Full HD (1920 × 1080) Refresh Rate: 60Hz Panel Type: HVA Panel HDR Support: HDR10 Picture Processor: AiPQ Processor Operating System: Google TV Google Assistant: Yes Google Cast (Chromecast Built-in): Yes Voice Control: Yes Dolby Audio: ",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/1111_24.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "TCL",
      "model": "tcl s51k fhd google tv with official warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips 75PQT8369/98 8300 Series 75 Inch 4K UHD QLED Google TV With Official Warranty",
    "brand": "Philips",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 584999,
    "compare_price": 600000,
    "cost_price": 479699,
    "stock": 17,
    "sku": "TM-PHILIPS-75PQT8369-98-8300-SERIES-75-INCH-4K-UHD-",
    "description": "Model Number: 75PQT8369/98 Series: 8300 Series Screen Size: 75 Inches Display Type: 4K UHD QLED Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 120Hz (Native) Aspect Ratio: 16:9 Picture Engine: Pixel Precise Ultra HD HDR Support: Dolby Vision, HDR10, HLG Operating System: Google T",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_raYTEge7yvsTESOHNzyiUyCnASTb9Yc70n5lRMi2.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Philips",
      "model": "philips 75pqt8369 98 8300 series 75 inch 4k uhd qled google tv with official war",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "75\"",
      "screensize": "75\"",
      "energylabel": ""
    }
  },
  {
    "name": "Philips 65PQT8169/98 Series 65 4K UHD QLED Smart Google TV With 1 Year Warranty",
    "brand": "Philips",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 323899,
    "compare_price": 340000,
    "cost_price": 265597,
    "stock": 18,
    "sku": "TM-PHILIPS-65PQT8169-98-SERIES-65-4K-UHD-QLED-SMART",
    "description": "Model Number: 65PQT8169/98 Series: 8100 Series Screen Size: 65 Inches Display Type: 4K UHD QLED Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 60Hz Aspect Ratio: 16:9 Picture Engine: Pixel Precise Ultra HD HDR Support: Dolby Vision, HDR10, HLG Operating System: Google TV Processo",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_N4mdEhreqjTQIrNqsWdMVnWAKqkTLk0Lz11qbTsM.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Philips",
      "model": "philips 65pqt8169 98 series 65 4k uhd qled smart google tv with 1 year warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips 55PQT8169/98 8100 Series 55 4K UHD QLED Google TV With 1 Year Warranty",
    "brand": "Philips",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 221999,
    "compare_price": 235000,
    "cost_price": 182039,
    "stock": 19,
    "sku": "TM-PHILIPS-55PQT8169-98-8100-SERIES-55-4K-UHD-QLED-",
    "description": "Model Number: 55PQT8169/98 Series: 8100 Series Screen Size: 55 Inches Display Type: 4K UHD QLED Resolution: 3840 × 2160 (4K UHD) Refresh Rate: 60Hz Aspect Ratio: 16:9 HDR Support: Dolby Vision, HDR10, HLG Operating System: Google TV Processor: Quad-Core Processor Internal Storage",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_q6jmAgtR8mC00lR1w9EfzoJ0AIircIV6R3thaUhi.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Philips",
      "model": "philips 55pqt8169 98 8100 series 55 4k uhd qled google tv with 1 year warranty",
      "warranty": "1 Year",
      "specifications": "Smart LED",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Anex AG-6135UB Deluxe Blender & Grinder With Official Warranty",
    "brand": "Anex",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 8499,
    "compare_price": 12000,
    "cost_price": 6969,
    "stock": 12,
    "sku": "TM-ANEX-AG-6135UB-DELUXE-BLENDER-GRINDER-WITH-OFFIC",
    "description": "220-240V 50/60Hz 500W 2 Years Warranty Features: Puree, blend, mix, crumb, liquify and grind quick and effective way. Blender Grinder 3 in1, Stainless-steel blades. 2 speed and pulse control. Full copper motor with safety device. Unbreakable jar, 1.5 Liter capacity.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_vFrZgyMpTWNgg9wEEt2nxR2gDylVeOn0kgulO2NK.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Anex",
      "model": "anex ag 6135ub deluxe blender grinder with official warranty",
      "warranty": "1 Year",
      "specifications": "Blender Grinder Chopper",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Anex AG-2022 Multi Cooker With Official Warranty",
    "brand": "Anex",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 11199,
    "compare_price": 15000,
    "cost_price": 9183,
    "stock": 13,
    "sku": "TM-ANEX-AG-2022-MULTI-COOKER-WITH-OFFICIAL-WARRANTY",
    "description": "4 liter capacity. Non-stick coating inner pot, easy for cooking and cleaning. 360 degree fast heating element for balance heating evenly. Different temperature settings to meet different needs. Its body is designed in such a way that it can be separated to allow for easy cleaning",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_yc9tChZxDD9h7qcWja9QnEoA1xpQ8S4K3NBeJOPK.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Anex",
      "model": "anex ag 2022 multi cooker with official warranty",
      "warranty": "1 Year",
      "specifications": "Electric Cooker",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips HD9137/91 Egg Boiler With Official Warranty",
    "brand": "Philips",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 13999,
    "compare_price": 18000,
    "cost_price": 11479,
    "stock": 14,
    "sku": "TM-PHILIPS-HD9137-91-EGG-BOILER-WITH-OFFICIAL-WARRA",
    "description": "Eggs cooked the way you enjoy them. Soft, medium, hard boiled and poached eggs cooked to perfection. With enough capacity for the whole family, its compact, practical design is also easy to clean and doesn't take up much space. Different cooking levels Family size 400 W power Poa",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_K1yuBpkQWyI3XOiAiqodxV24mIjLBniTG0VWW8q6.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Philips",
      "model": "philips hd9137 91 egg boiler with official warranty",
      "warranty": "1 Year",
      "specifications": "Kitchen Appliances",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "DeLonghi KG79 Burr Coffee Grinder Without Warranty",
    "brand": "De’Longhi",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 23999,
    "compare_price": 28500,
    "cost_price": 19679,
    "stock": 15,
    "sku": "TM-DELONGHI-KG79-BURR-COFFEE-GRINDER-WITH-OFFICIAL-",
    "description": "DeLonghi KG79 Burr Coffee Grinder Without Warranty Extract the best aroma with 2 grinding wheels Customise grinding with the 16-level adjustable grinding selector Automatic safety shut-off system when containers removed Grind just the coffee you need with the Cup Selector Easy to",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_ukeMrWyHwaMG3VJBgCeDsWzeojHElD7OZwF0AcL4.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "De’Longhi",
      "model": "delonghi kg79 burr coffee grinder with official warranty",
      "warranty": "1 Year",
      "specifications": "Coffee Grinder",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Anex AG-3157 Multifunction Food Processor With Official Warranty",
    "brand": "Anex",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 35229,
    "compare_price": 42000,
    "cost_price": 28888,
    "stock": 16,
    "sku": "TM-ANEX-AG-3157-MULTIFUNCTION-FOOD-PROCESSOR-WITH-O",
    "description": "Anex AG-3157 Multifunction Food Processor With Official Warranty 220-240V 50/60HZ 800-1100 watts 2 Years Warranty Features: A versatile food processor can quickly extract juice & easily chop, blend, slice, shred, grind & puree almost any food. Elegant plastic jug. 2 speed setting",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_3wmUamLBnTF3nmEi9dbtsRZGO2rcTvGgfolu3y6I.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Anex",
      "model": "anex ag 3157 multifunction food processor with official warranty",
      "warranty": "1 Year",
      "specifications": "Food Processor",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Anex AG-2132 Deluxe Sandwich Maker With Official Warranty",
    "brand": "Anex",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 7849,
    "compare_price": 10000,
    "cost_price": 6436,
    "stock": 17,
    "sku": "TM-ANEX-AG-2132-DELUXE-SANDWICH-MAKER-WITH-OFFICIAL",
    "description": "2 slice deep filled sandwich maker. Automatic temperature control. Power & indicator light for ready sandwiches. Non-stick coating sandwich plate for easy cleaning. Skid-resistant feet",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_jDr6Hv2qmk2niEISIZWmfdcM2SeG00AcwQ0zuPfA.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Anex",
      "model": "anex ag 2132 deluxe sandwich maker with official warranty",
      "warranty": "1 Year",
      "specifications": "Sandwich Maker",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Westpoint WF-262 Dual Hot Plate With Official Warranty",
    "brand": "Westpoint",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 11259,
    "compare_price": 16500,
    "cost_price": 9232,
    "stock": 18,
    "sku": "TM-WESTPOINT-WF-262-DUAL-HOT-PLATE-WITH-OFFICIAL-WA",
    "description": "Westpoint WF-262 Hot Plate double With Official Warranty Brand: Westpoint Model: WF-262 2 Years Official Warranty High quality cast iron plate Thermostat and on/off double controller power on light. Thermo fuse for safety use. Skid proof rubber feet Telemart offers you the best W",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_7LEaxxGdOQ3vBr7lTc4nMQCTpYwDN9uEZIr28NJP.gif",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Westpoint",
      "model": "westpoint wf 262 dual hot plate with official warranty",
      "warranty": "1 Year",
      "specifications": "Electric Cooker & Hot Plate",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Westpoint WF-9701 Hand Mixer With Official Warranty",
    "brand": "Westpoint",
    "category": "Kitchen Appliances",
    "unit": "pcs",
    "price": 5899,
    "compare_price": 7000,
    "cost_price": 4837,
    "stock": 19,
    "sku": "TM-WESTPOINT-WF-9701-HAND-MIXER-WITH-OFFICIAL-WARRA",
    "description": "5 Speeds with Turbo Function Prepare Delicious Soup, Sauces, Milk Shakes, etc Unique Safety Locking System Variable Speed Selector 200 Watts | 220 - 240V - 50Hz",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_lxztBl7qodg9KayIDBo8JzxanfCB9gtirQT3tTB7.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Westpoint",
      "model": "westpoint wf 9701 hand mixer with official warranty",
      "warranty": "1 Year",
      "specifications": "Hand Mixer",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Midea YL-2037S-B Water Dispenser with Refrigerator - Official Warranty",
    "brand": "Midea",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 40999,
    "compare_price": 50000,
    "cost_price": 33619,
    "stock": 14,
    "sku": "TM-MIDEA-YL-2037S-B-WATER-DISPENSER-WITH-REFRIGERAT",
    "description": "Category Details Brand Midea Colour White Material Stainless Steel Dimensions 31D x 35W x 100H cm Style Top Load Temperature Options 3 (Cold, Cool, Hot) Cooling Efficiency 20% Reduced Cooling Time Energy Efficiency 7% Less Energy Consumption Water Quality Fresh water with rich ox",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_UOUpaeCEUfP5tUjwq1FyILeD9RLpkQWNiQB7fWbs.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Midea",
      "model": "midea yl 2037s b water dispenser with refrigerator official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia HC-54 G 3 Taps Elegant Tempered Double Glass Door Water Dispenser With Official Warranty",
    "brand": "Super Asia",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 42299,
    "compare_price": 50000,
    "cost_price": 34685,
    "stock": 15,
    "sku": "TM-SUPER-ASIA-HC-54-G-3-TAPS-ELEGANT-TEMPERED-DOUBL",
    "description": "Elegant Tempered Double Glass Door Easy Water Dispensing with 3 Taps (Cold, Hot & Normal) Large Stainless Steel Water Tank LED Night Lights in Dispenser 20 Liter Large Refrigerator Capacity â€¢ Special Console with Easy Filling Jug & Bottle World Famous Energy Efficient DANFU Com",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_5UsUhCxiDZFQIGPLjlghV86P7JUnSMnKaj3BOvjL.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia hc 54 g 3 taps elegant tempered double glass door water dispenser wit",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia HC-53 G 3 Taps Water Dispenser With Official Warranty",
    "brand": "Super Asia",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 42299,
    "compare_price": 50000,
    "cost_price": 34685,
    "stock": 16,
    "sku": "TM-SUPER-ASIA-HC-53-G-3-TAPS-WATER-DISPENSER-WITH-O",
    "description": "Elegant Tempered Double Glass Door Easy Water Dispensing with 3 Taps (Cold, Hot & Normal) Large Stainless Steel Water Tank LED Night Lights in Dispenser 20 Liter Large Refrigerator Capacity (Special Console with Easy Filling Jug & Bottle) World Famous Energy Efficient DANFU Compr",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_JttNOiujTfTUvF6PIWcWNBIymZL4kT0gyT88Gsf8.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia hc 53 g 3 taps water dispenser with official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Super Asia HC-52 R Water Dispenser With Official Warranty",
    "brand": "Super Asia",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 41299,
    "compare_price": 46500,
    "cost_price": 33865,
    "stock": 17,
    "sku": "TM-SUPER-ASIA-HC-52-R-WATER-DISPENSER-WITH-OFFICIAL",
    "description": "Elegant Tempered Double Glass Door Easy Water Dispensing with 3 Taps (Cold, Hot & Normal) 20 Liter Large Refrigerator Capacity Special Console with Easy Filling Jug & Bottle World Famous Energy Efficient DANFU Compressor Hygienic & Anti-Bacterial (Food Grade Materials)",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_Dum9I5OkJZFr6UbF3IRpc0ef5V6L8ZhPAqxe2ElT.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Super Asia",
      "model": "super asia hc 52 r water dispenser with official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Dawlance WD-1060 Water Dispenser With Official Warranty (Without Refrigerator)",
    "brand": "Dawlance",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 42499,
    "compare_price": 50000,
    "cost_price": 34849,
    "stock": 18,
    "sku": "TM-DAWLANCE-WD-1060-WATER-DISPENSER-WITH-OFFICIAL-W",
    "description": "Top Load Design: Easy bottle installation Hot & Cold Water: Instant temperature options for daily use No Refrigerator Cabinet: More compact and energy-efficient Stainless Steel Tanks: Hygienic and long-lasting Large Capacity Tanks: 17% bigger cold tank 60% bigger hot tank Mechani",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_z9f3pQ5NWoB2pCZY5rffCDizaWkdZIay6ccLmNUy.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "dawlance wd 1060 water dispenser with official warranty without refrigerator",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Dawlance WD-1060 Water Dispenser with Refrigerator with Official Warranty",
    "brand": "Dawlance",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 45999,
    "compare_price": 50000,
    "cost_price": 37719,
    "stock": 19,
    "sku": "TM-DAWLANCE-WD-1060-WATER-DISPENSER-WITH-REFRIGERAT",
    "description": "Capacity Cooling Capacity 2 L/h Cold Water Tank Capacity 3 L Hot Water Capacity 4 L/h Hot Water Tank Capacity 1 L Design & Outlook Product Type Top Load Product Color Champagne Control System Mechanic Refrigerator Compartment Yes Energy Information Climate Class T Voltage (V) 220",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_IvqvBrpIhXrqUyYASJn2oEjABzvAMNl06apcbcVE.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "dawlance wd 1060 water dispenser with refrigerator with official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Dawlance WD-1051 Glass Door Water Dispenser with Official Warranty",
    "brand": "Dawlance",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 46999,
    "compare_price": 55000,
    "cost_price": 38539,
    "stock": 8,
    "sku": "TM-DAWLANCE-WD-1051-GLASS-DOOR-WATER-DISPENSER-WITH",
    "description": "Capacity Cooling Capacity 2.5 Cold Water Tank Capacity 3.5 Hot Water Capacity 6 Hot Water Tank Capacity 1.6 Design & Outlook Product Color White Control System Mechanic Refrigerator Compartment Yes Performance Cold Water Temperature 7-10 C Hot Water Temperature 85-95 Energy Infor",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_9lwHPGjk0oWyE0t9ThpezxwKIHDOZ7fRbShWztIu.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "dawlance wd 1051 glass door water dispenser with official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Dawlance WD-1035 Glass Door Bottom Load Water Dispenser with Official Warranty",
    "brand": "Dawlance",
    "category": "Water Dispensers",
    "unit": "pcs",
    "price": 57999,
    "compare_price": 65000,
    "cost_price": 47559,
    "stock": 9,
    "sku": "TM-DAWLANCE-WD-1035-GLASS-DOOR-BOTTOM-LOAD-WATER-DI",
    "description": "3 taps Bottom load water bottle system 3 liters cold and 2 liter hot capacity Heavy duty Glass front 3 year compressor warranty 1 year parts brand warranty Imported Stainless steel Glass Door All Premium Black 3 Faucets (Hot, Normal, Cool)",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_R71jt2292zFMaP4ZjmUpd5AvKNQCasuAcOpAcoTe.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "dawlance wd 1035 glass door bottom load water dispenser with official warranty",
      "warranty": "1 Year",
      "specifications": "Water Dispenser",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Tamoor Ceiling Fan 30W Super Pearl Model | Eco-Smart Series With Official Warranty",
    "brand": "Tamoor Fans",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 13499,
    "compare_price": 16500,
    "cost_price": 11069,
    "stock": 10,
    "sku": "TM-TAMOOR-CEILING-FAN-30W-SUPER-PEARL-MODEL-ECO-SMA",
    "description": "Model: Super Pearl Eco Smart Fan Size: 56 Inches Motor Type: PMSM (Permanent Magnet Synchronous Motor) Power Consumption: 30 Watts Input Voltage: 140V–240V AC Protection Voltage Range: 110V–280V AC Maximum Speed: Up to 350 RPM Speed Settings: 5 Blades: 3 Power Factor: 0.95 Motor ",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_gvb1KazfIBGajkqVYkliiPxiqqOdl7MIymV1eWqs.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Tamoor Fans",
      "model": "tamoor ceiling fan 30w super pearl model eco smart series with official warranty",
      "warranty": "1 Year",
      "specifications": "Ceiling Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Beurer LV 500 PureFlow 2-in-1 Air Purifier & Fan",
    "brand": "Beurer",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 99999,
    "compare_price": 110000,
    "cost_price": 81999,
    "stock": 11,
    "sku": "TM-BEURER-LV-500-PUREFLOW-2-IN-1-AIR-PURIFIER-FAN",
    "description": "A smart upgrade for your home – cleans the air and provides gentle cooling 2-in-1 air purifier and fan LV 500 PureFlow Enjoy fresh, clean air and soothing cooling from a device that can do both. The 2-in-1 fan with air purifier uses a three-layer system (pre-filter, H13 HEPA, act",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/MTk4MDYwbHY1MDAtcHJvZHVjdC1mcm9udC1ibHVlLWxpZ2h0LXYwMGQtYmV1cmVyLndlYnA.webp",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Beurer",
      "model": "beurer lv 500 pureflow 2 in 1 air purifier fan",
      "warranty": "1 Year",
      "specifications": "Air Dehumidifier",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Beurer LV 50 Fresh Breeze Personal Table Fan with Water Cooling",
    "brand": "Beurer",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 14999,
    "compare_price": 18000,
    "cost_price": 12299,
    "stock": 12,
    "sku": "TM-BEURER-LV-50-FRESH-BREEZE-WITH-OFFICIAL-WARRANTY",
    "description": "The compact and stylish LV 50 Fresh Breeze table fan ensures a fresh breeze in the office, when working from home or in your living space. With the practical carrying handle, the table fan is always ready to hand.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/LV_50_Produktbild.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Beurer",
      "model": "beurer lv 50 fresh breeze with official warranty",
      "warranty": "1 Year",
      "specifications": "Table Fan & Air Cooler",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips CX2050/00 Table Fan 2000 series With Official Warranty",
    "brand": "Philips",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 28499,
    "compare_price": 30779,
    "cost_price": 23369,
    "stock": 13,
    "sku": "TM-PHILIPS-CX2050-00-TABLE-FAN-2000-SERIES-WITH-OFF",
    "description": "Maximum cooling, minimum noise. The fan is designed to fit any home interior and cool your space quietly. Tailor your experience with 3 speeds, 2 modes, and a timer. Plus, enjoy enhanced air circulation with its tiltable head. 30% quieter(1) with SilentWings blade technology Fan ",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_eART0e7StZnLlFENN9uQ1gKmkFc3k0W0PXSbC5Y0.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Philips",
      "model": "philips cx2050 00 table fan 2000 series with official warranty",
      "warranty": "1 Year",
      "specifications": "Stand Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips CX3050/01 Table Fan 3000 series With Official Warranty",
    "brand": "Philips",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 35999,
    "compare_price": 40000,
    "cost_price": 29519,
    "stock": 14,
    "sku": "TM-PHILIPS-CX3050-01-TABLE-FAN-3000-SERIES-WITH-OFF",
    "description": "Maximum cooling, minimum noise. The fan is designed to fit any home interior and cool your space quietly. Tailor your experience with 3 speeds, 2 modes and a timer. Plus, enjoy enhanced air circulation with its tiltable head and rotation. 30% quieter(1) with SilentWings blade tec",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_RbziQlnDr4eqxE0CX4bkK3Q74rCKRVcP23vWWcE8.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Philips",
      "model": "philips cx3050 01 table fan 3000 series with official warranty",
      "warranty": "1 Year",
      "specifications": "Stand Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "NFC AC DC Ceiling Fan Brave Model 56 Inch Inverter Pure Copper Winding Remote Contro With Official",
    "brand": "Other",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 20899,
    "compare_price": 23500,
    "cost_price": 17137,
    "stock": 15,
    "sku": "TM-NFC-AC-DC-CEILING-FAN-BRAVE-MODEL-56-INCH-INVERT",
    "description": "Powerful Motor & Design Silent & Quiet Breeze High Airflow Design Energy Saver Blades: 5 Blades. Speed: 5 Speed. Rated Power on AC: 40-50 Watts. Input Voltage DC: 12V. Input Voltage AC: 90-290v. Rated Frequency: 50 Hz. DC Ampere: 3 Amps. RPMs: ≤380. Remote Control: (RF/IR). RF (R",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_9SJiPeY3sy3Al1CZyMAWngC4IelnVQXaccl61Mki.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Other",
      "model": "nfc ac dc ceiling fan brave model 56 inch inverter pure copper winding remote co",
      "warranty": "1 Year",
      "specifications": "Inverter Ceiling Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Tamoor Ceiling Fan 56 Inch Eco Smart 30 Watt | Water Proof Model 70 % Energy Saver Brand With Official Warranty",
    "brand": "Tamoor Fans",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 14799,
    "compare_price": 20000,
    "cost_price": 12135,
    "stock": 16,
    "sku": "TM-TAMOOR-CEILING-FAN-56-INCH-ECO-SMART-30-WATT-WAT",
    "description": "Tamoor Ceiling Fan 56 Inch Eco Smart 30 Watt | Water Proof Model 70 % Energy Saver Brand With Official Warranty. Available via Tenvo Electronics demo catalog.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_lu2Mczoj71iI3Uaw69TZRwnWH2ybv6nUqzJ4u2pS_d162f27c-8586-45a5-b797-16eb88f1c734.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Tamoor Fans",
      "model": "tamoor ceiling fan 56 inch eco smart 30 watt water proof model 70 energy saver b",
      "warranty": "1 Year",
      "specifications": "Ceiling Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Philips CX5535/11 Tower Fan 5000 series With Official Warranty",
    "brand": "Philips",
    "category": "Cooling & Fans",
    "unit": "pcs",
    "price": 49999,
    "compare_price": 53999,
    "cost_price": 40999,
    "stock": 17,
    "sku": "TM-PHILIPS-CX5535-11-TOWER-FAN-5000-SERIES-WITH-OFF",
    "description": "Enjoy powerful cooling with minimal noise and energy usage. Designed for high performance, this self-rotating fan brings a quick cooling effect to the entire room. Optionally, it can also infuse the air with your favorite scents. Performance, quality, and comfort Fan airflow 2230",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_lXqZvWqOk9kAcqGEwuuywK0ovApHqFmJzorPt9Ld.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Philips",
      "model": "philips cx5535 11 tower fan 5000 series with official warranty",
      "warranty": "1 Year",
      "specifications": "Stand Fan",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Jabra Speak 510 MS Wireless Bluetooth Speakerphone",
    "brand": "Jabra",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 35999,
    "compare_price": 410000,
    "cost_price": 29519,
    "stock": 11,
    "sku": "TM-JABRA-SPEAK-510-MS-WIRELESS-BLUETOOTH-SPEAKERPHO",
    "description": "USB Type-A & Bluetooth 3.0 Connectivity 360° Omnidirectional Microphone Certified for Skype for Business Up to 15 Hours Wireless Talk Time Echo Cancellation Programmable Smart Button Multi-Device Connectivity 250 Hz to 14 kHz Frequency Range Plug-and-Play, Portable Design",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/czone-20260304083719-87161-0-040326083726464.webp",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Jabra",
      "model": "jabra speak 510 ms wireless bluetooth speakerphone",
      "warranty": "1 Year",
      "specifications": "PC Speakers",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Logitech P710e Mobile Conference Speakerphone",
    "brand": "Logitech",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 30999,
    "compare_price": 38000,
    "cost_price": 25419,
    "stock": 12,
    "sku": "TM-LOGITECH-P710E-MOBILE-CONFERENCE-SPEAKERPHONE",
    "description": "Turn any workspace into an instant conference room. The Logitech Mobile Speakerphone P710e gives you hands-free calling and great audio for your phone or tablet. Noise-cancelling technology helps ensure everyone can hear and be heard. Pair up to eight BluetoothÂ® devices or conne",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_6Hyp73Jp4kvNTls0n5guDBn85BMZhRv3OAWTbDFk.png",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Logitech",
      "model": "logitech p710e mobile conference speakerphone",
      "warranty": "1 Year",
      "specifications": "Portble Speakers",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Faster Rainbow 4s Portable Wireless Speaker 10w",
    "brand": "Faster",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 4899,
    "compare_price": 6000,
    "cost_price": 4017,
    "stock": 13,
    "sku": "TM-FASTER-RAINBOW-4S-PORTABLE-WIRELESS-SPEAKER-10W",
    "description": "Brand : Faster Model No : Rainbow 4s Bluetooth : 5.1 Speaker Size : 4Ã¢â‚¬Â³ Input Current : DC 5V Battery : 1200 mAh Play Time : 2-3h (80% volume) Product Size : 229 *169 * 171 mm Multi Functional : Wireless/TF Card/Usb/AUX Input/Fm Warranty : 1 year",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Untitleddesign_15.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Faster",
      "model": "faster rainbow 4s portable wireless speaker 10w",
      "warranty": "1 Year",
      "specifications": "Bluetooth Speaker",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Faster G2000 RGB Lighting Dual Gaming Wireless Speakers 10W",
    "brand": "Faster",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 4399,
    "compare_price": 5500,
    "cost_price": 3607,
    "stock": 14,
    "sku": "TM-FASTER-G2000-RGB-LIGHTING-DUAL-GAMING-WIRELESS-S",
    "description": "Specifications Model Number: G2000 Speaker Type: Dual Gaming Wireless Speakers (2.0 Channel) Output Power: 10W (5W × 2) Bluetooth Version: 5.0 Lighting Effects: RGB Lighting Connectivity: Bluetooth, USB, 3.5mm AUX Power Input: DC 5V Controls: Power and Volume Control Material: AB",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_YKKk7H9iauhHGapS2fLKUL40pyAE5DxdYqgpVh3n.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Faster",
      "model": "faster g2000 rgb lighting dual gaming wireless speakers 10w",
      "warranty": "1 Year",
      "specifications": "Bluetooth Speaker",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Oraimo OBS-382 SpaceBox 8W FM Wireless Speaker",
    "brand": "Oraimo",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 3499,
    "compare_price": 5000,
    "cost_price": 2869,
    "stock": 15,
    "sku": "TM-ORAIMO-OBS-382-SPACEBOX-8W-FM-WIRELESS-SPEAKER",
    "description": "Product Parameters: Size: 146*72*50mm Weight: 280g Bluetooth version：V5.4 Battery Capacity：1800mAh/3.7V Frequency Response: 80Hz-20KHz Playtime: 5H(Max vol),16H(Med vol) Audio Output: 8W Transmission distance: 10m Material: Plastic & Metal Color: Space Grey Charging Input: Type-C",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_PhTgB8r6WVw3hfojDgCRMqZbJEqB4JZeGNq6v4a2.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Oraimo",
      "model": "oraimo obs 382 spacebox 8w fm wireless speaker",
      "warranty": "1 Year",
      "specifications": "Portble Speakers",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Oraimo OBS-53D Rover 12W FM Wireless Speaker",
    "brand": "Oraimo",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 5699,
    "compare_price": 9000,
    "cost_price": 4673,
    "stock": 16,
    "sku": "TM-ORAIMO-OBS-53D-ROVER-12W-FM-WIRELESS-SPEAKER",
    "description": "Size: 88*88*182mm Weight: 503g Bluetooth Version: V5.3 (More Fast &Stable) Frequency Response: 80Hz―20KHz Battery Capacity: 2400mAh Playtime: 6 hours（Lights On); 7 hours (Lights Off) Charging time: 3 hours Audio Output: 6W*2 Model: OBS-53D",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/oraimo-rover-12w-fm-wireless-speaker-obs-53d-pakis_1.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Oraimo",
      "model": "oraimo obs 53d rover 12w fm wireless speaker",
      "warranty": "1 Year",
      "specifications": "Portble Speakers",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Infinix XS01 Pocket Beat Wireless Bluetooth Speaker",
    "brand": "Infinix",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 1499,
    "compare_price": 2000,
    "cost_price": 1229,
    "stock": 17,
    "sku": "TM-INFINIX-XS01-POCKET-BEAT-WIRELESS-BLUETOOTH-SPEA",
    "description": "General Features Dimensions 105 x 35 x 185mm Weight N/A Model XS01 Display N/A Waterproof IPX5 Battery Type Lithium-Polymer Non-Removable Charging Time 3 Hours Connectivity Bluetooth Type V5.2 Bluetooth Range 10M / 30FT Frequency Range 80Hz-16kHz USB Compatibility Yes Mic Technol",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_rTxOEISOWMV5lZc0XDCoZUoXX4KjPI9YjjFypnuB.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Infinix",
      "model": "infinix xs01 pocket beat wireless bluetooth speaker",
      "warranty": "1 Year",
      "specifications": "Bluetooth Speaker",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Xiaomi Sound Party NS7 Portable Bluetooth Party Speaker",
    "brand": "Xiaomi",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 22999,
    "compare_price": 26500,
    "cost_price": 18859,
    "stock": 18,
    "sku": "TM-XIAOMI-SOUND-PARTY-NS7-PORTABLE-BLUETOOTH-PARTY-",
    "description": "Model : MDZ-39-DB Product Dimensions: 255 × 92 × 92 mm Design: Stylish and portable, with streamlined shape and a hidden handle — easy to carry for parties, trips, or outdoor fun. Net Weight: Approx. 1.2 kg (≈ 1200 g) Audio Output : Total 50 W — 35 W woofer + 15 W tweeter. Sound ",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/ddfsd85428f5sfasfaaa.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Xiaomi",
      "model": "xiaomi sound party ns7 portable bluetooth party speaker",
      "warranty": "1 Year",
      "specifications": "Portble Speakers",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Haier HSU -13LF 1 Ton DC Inverter Split Air Condition With Official Warranty",
    "brand": "Haier",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 95999,
    "compare_price": 105000,
    "cost_price": 78719,
    "stock": 13,
    "sku": "TM-HAIER-HSU-13LF-1-TON-DC-INVERTER-SPLIT-AIR-CONDI",
    "description": "Haier HSU -13LF 1 Ton DC Inverter Split Air Condition With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Untitleddesign_20_130dd02e-89eb-4f6b-9b91-dec6031dabe9.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Haier",
      "model": "haier-hsu-13lf-1-ton-dc-inverter-split-air-condition-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "1 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Haier HSU-13HFS T3 Pro 1 Ton DC Inverter AC With Official Warranty",
    "brand": "Haier",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 122499,
    "compare_price": 135000,
    "cost_price": 100449,
    "stock": 14,
    "sku": "TM-HAIER-HSU-13HFS-T3-PRO-1-TON-DC-INVERTER-AC-WITH",
    "description": "Haier HSU-13HFS T3 Pro 1 Ton DC Inverter AC With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Untitleddesign_23_7783cd9e-240a-43da-8e3d-a8c99fee3ed1.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Haier",
      "model": "haier-hsu-13hfs-t3-pro-1-ton-dc-inverter-ac-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "1 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "TCL 12SVN-AI-41 SaveIN AI T3 Series 1.0 Ton DC Inverter Air Conditioner With Official Warranty",
    "brand": "TCL",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 113999,
    "compare_price": 125000,
    "cost_price": 93479,
    "stock": 15,
    "sku": "TM-TCL-12SVN-AI-41-SAVEIN-AI-T3-SERIES-1-0-TON-DC-I",
    "description": "TCL 12SVN-AI-41 SaveIN AI T3 Series 1.0 Ton DC Inverter Air Conditioner With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_kBFE4HoMcwwaIVe3OBn2YyeaOlsd3xtJXGX0Ysg1.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "TCL",
      "model": "tcl-12svn-ai-41-savein-ai-t3-series-1-0-ton-dc-inverter-air-conditioner-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "1.0 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Milli Legacy 9413 Pumps For Women",
    "brand": "Milli Legacy",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 1399,
    "compare_price": 2500,
    "cost_price": 1147,
    "stock": 16,
    "sku": "TM-MILLI-LEGACY-9413-PUMPS-FOR-WOMEN",
    "description": "Milli Legacy 9413 Pumps For Women. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Untitleddesign-2026-07-14T134616.171.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Milli Legacy",
      "model": "milli-legacy-9413-pumps-for-women",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Samsung AR24ASFZGWKZ 2 Ton Wall Mount Inverter AC T3 Series With Official Warranty",
    "brand": "Samsung",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 326999,
    "compare_price": 350000,
    "cost_price": 268139,
    "stock": 17,
    "sku": "TM-SAMSUNG-AR24ASFZGWKZ-2-TON-WALL-MOUNT-INVERTER-A",
    "description": "Samsung AR24ASFZGWKZ 2 Ton Wall Mount Inverter AC T3 Series With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_NZtGtEbYGMuFFJoxpHJ6Q3G3nCxaQxP2F4WO1vX6.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Samsung",
      "model": "samsung-ar24asfzgwkz-2-ton-wall-mount-inverter-ac-t3-series-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "2 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Samsung AR12TSHZGWKY 1 Ton Inverter AC T3 Series With Official Warranty",
    "brand": "Samsung",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 199999,
    "compare_price": 215000,
    "cost_price": 163999,
    "stock": 18,
    "sku": "TM-SAMSUNG-AR12TSHZGWKY-1-TON-INVERTER-AC-T3-SERIES",
    "description": "Samsung AR12TSHZGWKY 1 Ton Inverter AC T3 Series With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_NZtGtEbYGMuFFJoxpHJ6Q3G3nCxaQxP2F4WO1vX6.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Samsung",
      "model": "samsung-ar12tshzgwky-1-ton-inverter-ac-t3-series-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "1 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Midea 12HRFN1  Xtreme Plus Heat & Cool Split Air Conditioner With Official Warranty",
    "brand": "Telemart",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 125999,
    "compare_price": 135000,
    "cost_price": 103319,
    "stock": 19,
    "sku": "TM-MIDEA-12HRFN1-XTREME-PLUS-HEAT-COOL-SPLIT-AIR-CO",
    "description": "Midea 12HRFN1  Xtreme Plus Heat & Cool Split Air Conditioner With Official Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Midea1Ton12HRFN1-QC6XtremePlusInverterAC.webp",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": false,
    "domain_data": {
      "brand": "Telemart",
      "model": "midea-12hrfn1-xtreme-plus-heat-cool-split-air-conditioner-with-official-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "",
      "screensize": "",
      "energylabel": ""
    }
  },
  {
    "name": "Midea 18HRFN8 Breezeless  1.5 Ton Inverter Air Conditioner With Offical Warranty",
    "brand": "Midea",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 168999,
    "compare_price": 180000,
    "cost_price": 138579,
    "stock": 8,
    "sku": "TM-MIDEA-18HRFN8-BREEZELESS-1-5-TON-INVERTER-AIR-CO",
    "description": "Midea 18HRFN8 Breezeless  1.5 Ton Inverter Air Conditioner With Offical Warranty. Official warranty support.",
    "image_url": "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/lg_Q7ISiBlZcZW2pk45T1Rokr0Apxr15Km9al4Zf24F.jpg",
    "imageCredit": "Telemart / Shopify CDN",
    "is_featured": true,
    "domain_data": {
      "brand": "Midea",
      "model": "midea-18hrfn8-breezeless-1-5-ton-inverter-air-conditioner-with-offical-warranty",
      "warranty": "1 Year",
      "specifications": "Air Conditioner",
      "capacity": "1.5 Ton",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "YOLO Play 2 HD Explosive Sound",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 1399,
    "compare_price": 1511,
    "cost_price": 1147,
    "stock": 18,
    "sku": "TE-YOLO-PLAY-2-HD-EXPLOSIVE-SOUND",
    "description": "YOLO Play 2 HD Explosive Sound. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": true,
    "domain_data": {
      "model": "Play 2 HD Explosive Sound",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Play 1 Travel and Party Booster",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 4000,
    "compare_price": 4320,
    "cost_price": 3280,
    "stock": 18,
    "sku": "TE-YOLO-PLAY-1-TRAVEL-AND-PARTY-BOOSTER",
    "description": "YOLO Play 1 Travel and Party Booster. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": true,
    "domain_data": {
      "model": "Play 1 Travel and Party Booster",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Buddy Experience The Magic",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 5999,
    "compare_price": 6479,
    "cost_price": 4919,
    "stock": 18,
    "sku": "TE-YOLO-BUDDY-EXPERIENCE-THE-MAGIC",
    "description": "YOLO Buddy Experience The Magic. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": true,
    "domain_data": {
      "model": "Buddy Experience The Magic",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Pulse FEEL THE MUSIC SPEAKER",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 6999,
    "compare_price": 7559,
    "cost_price": 5739,
    "stock": 18,
    "sku": "TE-YOLO-PULSE-FEEL-THE-MUSIC-SPEAKER",
    "description": "YOLO Pulse FEEL THE MUSIC SPEAKER. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Pulse FEEL THE MUSIC SPEAKER",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Watch Pro | Smart Watch With Bluetooth Calling",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 8999,
    "compare_price": 9719,
    "cost_price": 7379,
    "stock": 18,
    "sku": "TE-YOLO-WATCH-PRO-SMART-WATCH-WITH-BLUETOOT",
    "description": "YOLO Watch Pro | Smart Watch With Bluetooth Calling. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Watch Pro | Smart Watch With Bluetooth Calling",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Watch Pro Max | Bigger Bolder & Faster",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 9999,
    "compare_price": 10799,
    "cost_price": 8199,
    "stock": 18,
    "sku": "TE-YOLO-WATCH-PRO-MAX-BIGGER-BOLDER-FASTER",
    "description": "YOLO Watch Pro Max | Bigger Bolder & Faster. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Watch Pro Max | Bigger Bolder & Faster",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Fortuner Pro | The Next Big Thing",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 10699,
    "compare_price": 11555,
    "cost_price": 8773,
    "stock": 18,
    "sku": "TE-YOLO-FORTUNER-PRO-THE-NEXT-BIG-THING",
    "description": "YOLO Fortuner Pro | The Next Big Thing. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Fortuner Pro | The Next Big Thing",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Thunder | Sleek Seamless Iconic Class that stands apart",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 8999,
    "compare_price": 9719,
    "cost_price": 7379,
    "stock": 18,
    "sku": "TE-YOLO-THUNDER-SLEEK-SEAMLESS-ICONIC-CLASS",
    "description": "YOLO Thunder | Sleek Seamless Iconic Class that stands apart. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Thunder | Sleek Seamless Iconic Class that stands apart",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Epic | You Are Built To Be EPIC",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 7699,
    "compare_price": 8315,
    "cost_price": 6313,
    "stock": 18,
    "sku": "TE-YOLO-EPIC-YOU-ARE-BUILT-TO-BE-EPIC",
    "description": "YOLO Epic | You Are Built To Be EPIC. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Epic | You Are Built To Be EPIC",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "YOLO Ultron | Genuine Leather Strap",
    "brand": "YOLO",
    "category": "Gadgets & Wearables",
    "unit": "pcs",
    "price": 12999,
    "compare_price": 14039,
    "cost_price": 10659,
    "stock": 18,
    "sku": "TE-YOLO-ULTRON-GENUINE-LEATHER-STRAP",
    "description": "YOLO Ultron | Genuine Leather Strap. Genuine YOLO gadgets & wearables with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "Ultron | Genuine Leather Strap",
      "warranty": "1 Year",
      "specifications": "",
      "capacity": "",
      "screensize": "",
      "brand": "YOLO"
    }
  },
  {
    "name": "PEL -18k Turbo DC Ultra InverterOn 1.5 Ton H&C Grand Clearance",
    "brand": "PEL",
    "category": "Air Conditioners",
    "unit": "pcs",
    "price": 143500,
    "compare_price": 154980,
    "cost_price": 117670,
    "stock": 6,
    "sku": "TE-PEL-18K-TURBO-DC-ULTRA-INVERTERON-1-5-TO",
    "description": "PEL -18k Turbo DC Ultra InverterOn 1.5 Ton H&C Grand Clearance. Genuine PEL air conditioners with official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "model": "18k Turbo DC Ultra InverterOn 1.5 Ton H&C Grand Clearance",
      "warranty": "1 Year",
      "specifications": "Inverter, Hot & Cold",
      "capacity": "1.5 Ton",
      "screensize": "",
      "brand": "PEL"
    }
  },
  {
    "name": "Haier 12 cu ft Inverter Refrigerator",
    "brand": "Haier",
    "category": "Refrigerators",
    "unit": "pcs",
    "price": 89500,
    "compare_price": 96500,
    "cost_price": 73400,
    "stock": 5,
    "sku": "TE-HAIER-REF-12CFT-INV",
    "description": "Energy-efficient inverter refrigerator for family kitchens. Official warranty support.",
    "image_url": "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": true,
    "domain_data": {
      "brand": "Haier",
      "model": "HRF-12INV",
      "warranty": "1 Year",
      "specifications": "Inverter, frost free",
      "capacity": "12 cu ft",
      "screensize": "",
      "energylabel": "Inverter"
    }
  },
  {
    "name": "Samsung 43\" Crystal UHD Smart LED TV",
    "brand": "Samsung",
    "category": "LED TVs",
    "unit": "pcs",
    "price": 112000,
    "compare_price": 125000,
    "cost_price": 91800,
    "stock": 8,
    "sku": "TE-SAMSUNG-43-CUHD",
    "description": "43-inch Crystal UHD smart TV with vivid picture and streaming apps.",
    "image_url": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": true,
    "domain_data": {
      "brand": "Samsung",
      "model": "43CUHD",
      "warranty": "1 Year",
      "specifications": "4K UHD, Smart",
      "capacity": "",
      "screensize": "43\"",
      "energylabel": "A"
    }
  },
  {
    "name": "Dawlance 8 KG Fully Automatic Washing Machine",
    "brand": "Dawlance",
    "category": "Washing Machines",
    "unit": "pcs",
    "price": 68500,
    "compare_price": 74000,
    "cost_price": 56200,
    "stock": 7,
    "sku": "TE-DAWLANCE-WM-8KG",
    "description": "Fully automatic washing machine with reliable wash cycles for daily laundry.",
    "image_url": "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?w=900&q=80&auto=format&fit=crop",
    "imageCredit": "Unsplash demo",
    "is_featured": false,
    "domain_data": {
      "brand": "Dawlance",
      "model": "DWM-8FA",
      "warranty": "1 Year",
      "specifications": "Fully automatic",
      "capacity": "8 KG",
      "screensize": "",
      "energylabel": "A+"
    }
  }
];

/** Marketing / gallery hero */
export const ELECTRONICS_MARKETING_HERO_IMAGE = "https://cdn.shopify.com/s/files/1/0830/0897/9164/files/Untitleddesign_20_130dd02e-89eb-4f6b-9b91-dec6031dabe9.jpg";

export const ELECTRONICS_DEMO_HERO_SLIDES = [
  {
    title: 'Power your home with genuine electronics',
    subtitle: 'Appliances and gadgets with official warranty and Karachi delivery.',
    image: ELECTRONICS_MARKETING_HERO_IMAGE,
    cta: 'Shop appliances',
    href: '/products',
  },
  {
    title: 'Gadgets and wearables for every day',
    subtitle: 'Smart watches, speakers, and accessories from trusted brands.',
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=80&auto=format&fit=crop",
    cta: 'Shop gadgets',
    href: '/products?category=gadgets-wearables',
  },
  {
    title: 'Ask about easy installment plans',
    subtitle: 'Enquire via contact. Our team will help you choose a plan that fits.',
    image: ELECTRONICS_MARKETING_HERO_IMAGE,
    cta: 'Installment enquiry',
    href: '/contact?subject=installment',
  },
];
