/**
 * Curated appliance SKUs that supplement archive/electronics.html gadgets.
 * Merged by build-electronics-seed-catalog.mjs and rich catalog exports.
 * Images: Unsplash (license-safe demos) — not Imran brand marks.
 */
export const ELECTRONICS_SUPPLEMENT_PRODUCTS = [
  {
    name: 'Haier 12 cu ft Inverter Refrigerator',
    brand: 'Haier',
    category: 'Refrigerators',
    unit: 'pcs',
    price: 89500,
    compare_price: 96500,
    cost_price: 73400,
    stock: 5,
    sku: 'TE-HAIER-REF-12CFT-INV',
    description: 'Energy-efficient inverter refrigerator for family kitchens. Official warranty support.',
    image_url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: true,
    domain_data: {
      brand: 'Haier',
      model: 'HRF-12INV',
      warranty: '1 Year',
      specifications: 'Inverter, frost free',
      capacity: '12 cu ft',
      screensize: '',
      energylabel: 'Inverter',
    },
  },
  {
    name: 'Samsung 43" Crystal UHD Smart LED TV',
    brand: 'Samsung',
    category: 'LED TVs',
    unit: 'pcs',
    price: 112000,
    compare_price: 125000,
    cost_price: 91800,
    stock: 8,
    sku: 'TE-SAMSUNG-43-CUHD',
    description: '43-inch Crystal UHD smart TV with vivid picture and streaming apps.',
    image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: true,
    domain_data: {
      brand: 'Samsung',
      model: '43CUHD',
      warranty: '1 Year',
      specifications: '4K UHD, Smart',
      capacity: '',
      screensize: '43"',
      energylabel: 'A',
    },
  },
  {
    name: 'Dawlance 8 KG Fully Automatic Washing Machine',
    brand: 'Dawlance',
    category: 'Washing Machines',
    unit: 'pcs',
    price: 68500,
    compare_price: 74000,
    cost_price: 56200,
    stock: 7,
    sku: 'TE-DAWLANCE-WM-8KG',
    description: 'Fully automatic washing machine with reliable wash cycles for daily laundry.',
    image_url: 'https://images.unsplash.com/photo-1626806787461-94efa66c42c8?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: false,
    domain_data: {
      brand: 'Dawlance',
      model: 'DWM-8FA',
      warranty: '1 Year',
      specifications: 'Fully automatic',
      capacity: '8 KG',
      screensize: '',
      energylabel: 'A+',
    },
  },
  {
    name: 'Orient 25L Solo Microwave Oven',
    brand: 'Orient',
    category: 'Kitchen Appliances',
    unit: 'pcs',
    price: 18900,
    compare_price: 21500,
    cost_price: 15500,
    stock: 14,
    sku: 'TE-ORIENT-MW-25L',
    description: 'Compact solo microwave for everyday reheating and cooking.',
    image_url: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: false,
    domain_data: {
      brand: 'Orient',
      model: 'OMW-25',
      warranty: '1 Year',
      specifications: 'Solo microwave',
      capacity: '25L',
      screensize: '',
      energylabel: '',
    },
  },
  {
    name: 'Gree 1 Ton Inverter AC Hot & Cold',
    brand: 'Gree',
    category: 'Air Conditioners',
    unit: 'pcs',
    price: 128500,
    compare_price: 139000,
    cost_price: 105400,
    stock: 4,
    sku: 'TE-GREE-AC-1T-INV',
    description: '1 ton inverter AC with hot and cold modes for year-round comfort.',
    image_url: 'https://images.unsplash.com/photo-1631545806609-7a0f4b8a0c8f?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: true,
    domain_data: {
      brand: 'Gree',
      model: 'Gree-1T-HC',
      warranty: '1 Year',
      specifications: 'Inverter, Hot & Cold',
      capacity: '1 Ton',
      screensize: '',
      energylabel: 'Inverter',
    },
  },
  {
    name: 'Kenwood Ceiling Fan 56"',
    brand: 'Kenwood',
    category: 'Cooling & Fans',
    unit: 'pcs',
    price: 8500,
    compare_price: 9500,
    cost_price: 6970,
    stock: 25,
    sku: 'TE-KENWOOD-FAN-56',
    description: '56-inch ceiling fan for quiet, efficient room cooling.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80&auto=format&fit=crop',
    imageCredit: 'Unsplash demo',
    is_featured: false,
    domain_data: {
      brand: 'Kenwood',
      model: 'KF-56',
      warranty: '1 Year',
      specifications: 'Ceiling fan',
      capacity: '56"',
      screensize: '',
      energylabel: '',
    },
  },
];
