/**
 * Tenvo Footwear demo / registration catalog.
 * Imported SKUs from Khazanay archive handles; local PK brands for country-aware mix.
 * Images: Khazanay CDN when scraped, Nike archive heroes for marketing assets.
 */
import {
  FOOTWEAR_HERO_IMAGES,
  FOOTWEAR_CATEGORY_IMAGES,
  FOOTWEAR_CONDITION_IMAGES,
} from './footwearArchiveAssets.js';

/** @type {string[]} */
export const FOOTWEAR_SEED_CATEGORIES = [
  "Men's Shoes",
  "Women's Shoes",
  "Kids Shoes",
  'Sports Shoes',
  'Casual',
  'Sandals',
  'Boots',
  'Orthopedic',
  'Accessories',
  'Leather Goods',
];

/**
 * @param {object} partial
 * @returns {Record<string, unknown>}
 */
function shoeProduct(partial) {
  const {
    name,
    brand,
    category,
    sku,
    price,
    compare_price,
    unit = 'pair',
    stock = 16,
    featured = false,
    image,
    description,
    domain_data = {},
  } = partial;
  const cost = Math.round(Number(price) * 0.72);
  return {
    name,
    brand,
    category,
    unit,
    price,
    compare_price: compare_price ?? Math.round(Number(price) * 1.4),
    cost_price: cost,
    stock,
    sku,
    description:
      description ||
      `${name}. ${brand} ${String(category || 'footwear').toLowerCase()} with size ${domain_data.size || 'as marked'}.`,
    image_url: image,
    imageCredit: domain_data.sourcing === 'local' ? 'Local brand seed' : 'Khazanay archive reference',
    is_featured: featured,
    domain_data: {
      articlenumber: domain_data.articlenumber || sku,
      size: domain_data.size || '',
      color: domain_data.color || '',
      material: domain_data.material || 'Mixed',
      style: domain_data.style || 'Casual',
      gender: domain_data.gender || 'unisex',
      condition: domain_data.condition || 'premium',
      sourcing: domain_data.sourcing || 'imported',
      brand: brand,
      ...domain_data,
    },
  };
}

/** Marketing hero for gallery / demo meta */
export const FOOTWEAR_MARKETING_HERO_IMAGE = FOOTWEAR_HERO_IMAGES.hero1;

/** @type {Array<Record<string, unknown>>} */
export const FOOTWEAR_SEED_PRODUCTS = [
  shoeProduct({
    name: "New Balance 2002R",
    brand: "New Balance",
    category: "Casual",
    sku: "TF-SHOE-001",
    price: 10799,
    compare_price: 14399,
    stock: 12,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/b7aa703e-83a6-4247-a54c-d8a94c1b8edd-Img-shoe_18f60585-fe3d-4841-8200-e607b9f53572.jpg?v=1785258854",
    description: "New Balance 2002R. Authentic New Balance casual. Size EUR 44. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-001",
      size: "EUR 44",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Skechers Uno - Stand On Air",
    brand: "Skechers",
    category: "Casual",
    sku: "TF-SHOE-002",
    price: 8099,
    compare_price: 10799,
    stock: 13,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/3ca0ece6-4507-47fd-8d4b-cd7c7c673d39-Img-shoe.jpg?v=1785258840",
    description: "Skechers Uno - Stand On Air. Authentic Skechers casual. Size EUR 40. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-002",
      size: "EUR 40",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Adidas Zx 700 HD",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-003",
    price: 8099,
    compare_price: 10799,
    stock: 14,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/82e98005-4a5a-4005-8190-5dc4d0c8407a-861185-1.jpg?v=1785258814",
    description: "Adidas Zx 700 HD. Authentic Adidas casual. Size EUR 44.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-003",
      size: "EUR 44.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Skechers Gowalk Arch Fit",
    brand: "Skechers",
    category: "Sports Shoes",
    sku: "TF-SHOE-004",
    price: 7699,
    compare_price: 10265,
    stock: 15,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/a7f04d02-d81d-4eb9-8706-5de767e4f7a9-861186-1.jpg?v=1785258802",
    description: "Skechers Gowalk Arch Fit. Authentic Skechers sports. Size EUR 39. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-004",
      size: "EUR 39",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Skechers Skech-air Dynamight",
    brand: "Skechers",
    category: "Casual",
    sku: "TF-SHOE-005",
    price: 7699,
    compare_price: 10265,
    stock: 16,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/953315d6-1da7-485e-a58a-db0828972483-861356-1.jpg?v=1785258776",
    description: "Skechers Skech-air Dynamight. Authentic Skechers casual. Size EUR 40. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-005",
      size: "EUR 40",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Skechers Summits",
    brand: "Skechers",
    category: "Casual",
    sku: "TF-SHOE-006",
    price: 7799,
    compare_price: 10399,
    stock: 17,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/e222eaaa-fb42-465d-820d-9e31fb401b7d-861359-1.jpg?v=1785258763",
    description: "Skechers Summits. Authentic Skechers casual. Size EUR 44. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-006",
      size: "EUR 44",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Hummel .",
    brand: "Hummel",
    category: "Casual",
    sku: "TF-SHOE-007",
    price: 7799,
    compare_price: 10399,
    stock: 18,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/9df0359f-d3d9-4410-bd9f-9fe5c51cb759-861360-1.jpg?v=1785258749",
    description: "Hummel .. Authentic Hummel casual. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-007",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Hummel",
    },
  }),
  shoeProduct({
    name: "Skechers Delson 3.0",
    brand: "Skechers",
    category: "Casual",
    sku: "TF-SHOE-008",
    price: 9299,
    compare_price: 12399,
    stock: 19,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/88b00f37-052f-4627-bbae-407a548518f8-861370-1.jpg?v=1785258735",
    description: "Skechers Delson 3.0. Authentic Skechers casual. Size EUR 44. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-008",
      size: "EUR 44",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Under Armour Charged Pursuit 2",
    brand: "Under Armour",
    category: "Sports Shoes",
    sku: "TF-SHOE-009",
    price: 7699,
    compare_price: 10265,
    stock: 20,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/359da3d1-9064-418e-99bf-0580fcf66f69-Img-shoe.jpg?v=1785258721",
    description: "Under Armour Charged Pursuit 2. Authentic Under Armour sports. Size EUR 40.5. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-009",
      size: "EUR 40.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Under Armour",
    },
  }),
  shoeProduct({
    name: "ASICS Rapid",
    brand: "Asics",
    category: "Casual",
    sku: "TF-SHOE-010",
    price: 8399,
    compare_price: 11199,
    stock: 21,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/7f31ac51-763f-4f0f-9579-ba4c650f096b-861377-1.jpg?v=1785258709",
    description: "ASICS Rapid. Authentic Asics casual. Size EUR 42. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-010",
      size: "EUR 42",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Asics",
    },
  }),
  shoeProduct({
    name: "New Balance 997H",
    brand: "New Balance",
    category: "Casual",
    sku: "TF-SHOE-011",
    price: 9499,
    compare_price: 12665,
    stock: 22,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/847ff544-d3d5-4f94-93a7-0089127fea4f-Img-shoe.jpg?v=1785258696",
    description: "New Balance 997H. Authentic New Balance casual. Size EUR 41.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-011",
      size: "EUR 41.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Adidas Switch Fwd",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-012",
    price: 10399,
    compare_price: 13865,
    stock: 23,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/0fa09380-6d53-4795-ae4a-50a9a043bf56-Img-shoe.jpg?v=1785258656",
    description: "Adidas Switch Fwd. Authentic Adidas casual. Size EUR 40.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-012",
      size: "EUR 40.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Nike Court Vision Low Next Nature",
    brand: "Nike",
    category: "Casual",
    sku: "TF-SHOE-013",
    price: 8599,
    compare_price: 11465,
    stock: 24,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/img-shoe-dbf108e9-7605-441c-a1d5-b401ceeff3e9.jpg?v=1785258644",
    description: "Nike Court Vision Low Next Nature. Authentic Nike casual. Size EUR 40.5. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-013",
      size: "EUR 40.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Altra Olympus 4",
    brand: "Altra",
    category: "Sports Shoes",
    sku: "TF-SHOE-014",
    price: 12899,
    compare_price: 17199,
    stock: 25,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/4af23f2b-22d6-40b3-a336-2f51f8c59617-861420-1.jpg?v=1785258630",
    description: "Altra Olympus 4. Authentic Altra sports. Size EUR 42. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-014",
      size: "EUR 42",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Altra",
    },
  }),
  shoeProduct({
    name: "New Balance 574",
    brand: "New Balance",
    category: "Casual",
    sku: "TF-SHOE-015",
    price: 7499,
    compare_price: 9999,
    stock: 26,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/459d1b04-cd76-459b-b104-d504bc7ff692-861426-1.jpg?v=1785258618",
    description: "New Balance 574. Authentic New Balance casual. Size EUR 42.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-015",
      size: "EUR 42.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Adidas Breaknet 2.0",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-016",
    price: 8599,
    compare_price: 11465,
    stock: 27,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/e2de721d-f228-4079-806c-6da53bf68a8a-Img-shoe.jpg?v=1785258604",
    description: "Adidas Breaknet 2.0. Authentic Adidas casual. Size EUR 41.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-016",
      size: "EUR 41.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Adidas Campus 00S",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-017",
    price: 8099,
    compare_price: 10799,
    stock: 28,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/0bf9b481-ea77-4fd3-94d8-fd12e31a1421-Img-shoe.jpg?v=1785258591",
    description: "Adidas Campus 00S. Authentic Adidas casual. Size EUR 44. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-017",
      size: "EUR 44",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Puma St Runner V4 Nylon",
    brand: "Puma",
    category: "Sports Shoes",
    sku: "TF-SHOE-018",
    price: 7099,
    compare_price: 9465,
    stock: 29,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/8d3fa4d6-aed1-4849-bf02-4615da9c7be9-Img-shoe.jpg?v=1785258578",
    description: "Puma St Runner V4 Nylon. Authentic Puma sports. Size EUR 40. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-018",
      size: "EUR 40",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Puma",
    },
  }),
  shoeProduct({
    name: "Nike Zoom Mercurial Vapor 15",
    brand: "Nike",
    category: "Sports Shoes",
    sku: "TF-SHOE-019",
    price: 9499,
    compare_price: 12665,
    stock: 12,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/de943d9f-fa20-44f8-9f22-4937fc229606-861446-1.jpg?v=1785258550",
    description: "Nike Zoom Mercurial Vapor 15. Authentic Nike sports. Size EUR 42. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-019",
      size: "EUR 42",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Adidas Treziod 2.0",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-020",
    price: 16199,
    compare_price: 22499,
    stock: 13,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/f9affa0d-6395-476d-a550-00be70d42fb8-Img-shoe.jpg?v=1785258537",
    description: "Adidas Treziod 2.0. Authentic Adidas casual. Size EUR 44. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-020",
      size: "EUR 44",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "On Cloud X 4",
    brand: "On",
    category: "Sports Shoes",
    sku: "TF-SHOE-021",
    price: 3499,
    compare_price: 4999,
    stock: 14,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/cdf3bd4b-d726-4333-8e45-49b03da486ba-Img-shoe.jpg?v=1785258524",
    description: "On Cloud X 4. Authentic On sports. Size EUR 47. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-021",
      size: "EUR 47",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "On",
    },
  }),
  shoeProduct({
    name: "New Balance Fresh Foam 680V7",
    brand: "New Balance",
    category: "Sports Shoes",
    sku: "TF-SHOE-022",
    price: 7399,
    compare_price: 9865,
    stock: 15,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/b7eb3a55-264e-4691-be65-fa5115482207-861468-1.jpg?v=1785258510",
    description: "New Balance Fresh Foam 680V7. Authentic New Balance sports. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-022",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Nike Air Zoom Pegasus 39",
    brand: "Nike",
    category: "Sports Shoes",
    sku: "TF-SHOE-023",
    price: 9699,
    compare_price: 12932,
    stock: 16,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/7a551053-d6d7-4256-9cce-89ce7964feef-Img-shoe.jpg?v=1785258498",
    description: "Nike Air Zoom Pegasus 39. Authentic Nike sports. Size EUR 44.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-023",
      size: "EUR 44.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Nike Air Force 1 Low",
    brand: "Nike",
    category: "Casual",
    sku: "TF-SHOE-024",
    price: 9699,
    compare_price: 12932,
    stock: 17,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/18134a8b-9c02-4e42-913a-94aaad60df68-Img-shoe.jpg?v=1785258484",
    description: "Nike Air Force 1 Low. Authentic Nike casual. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-024",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "New Balance Fresh Foam Arishi V4",
    brand: "New Balance",
    category: "Sports Shoes",
    sku: "TF-SHOE-025",
    price: 9299,
    compare_price: 12399,
    stock: 18,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/16801218-52c5-4f17-a645-27a4fd716376-861497-1.jpg?v=1785258471",
    description: "New Balance Fresh Foam Arishi V4. Authentic New Balance sports. Size EUR 41.5. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-025",
      size: "EUR 41.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Skechers D'lites - Me Time",
    brand: "Skechers",
    category: "Women's Shoes",
    sku: "TF-SHOE-026",
    price: 8099,
    compare_price: 10799,
    stock: 19,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/f5f61186-0954-4051-bcf5-cfcc7ca012ce-861501-1.jpg?v=1785258459",
    description: "Skechers D'lites - Me Time. Authentic Skechers casual. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-026",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "women",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "Nike Air Max Pre-day Se",
    brand: "Nike",
    category: "Casual",
    sku: "TF-SHOE-027",
    price: 10199,
    compare_price: 13599,
    stock: 20,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/946e2cde-e012-4c85-b9ad-df58ff10e51f-Img-shoe.jpg?v=1785258446",
    description: "Nike Air Max Pre-day Se. Authentic Nike casual. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-027",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Avia Memory Foam",
    brand: "Avia",
    category: "Orthopedic",
    sku: "TF-SHOE-028",
    price: 5499,
    compare_price: 7332,
    stock: 21,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/65d13036-ad4f-4b14-8aed-6551e1b515a7-861509-1.jpg?v=1785258432",
    description: "Avia Memory Foam. Authentic Avia orthopedic. Size EUR 39.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-028",
      size: "EUR 39.5",
      color: "Multi",
      material: "Mixed",
      style: "Orthopedic",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Avia",
    },
  }),
  shoeProduct({
    name: "Adidas Combat Speed 4",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-029",
    price: 8599,
    compare_price: 11465,
    stock: 22,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/2fa54e50-5ff9-4f9b-bc09-c3152476a5c0-Img-shoe.jpg?v=1785258420",
    description: "Adidas Combat Speed 4. Authentic Adidas casual. Size EUR 38. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-029",
      size: "EUR 38",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Adidas Break Start",
    brand: "Adidas",
    category: "Casual",
    sku: "TF-SHOE-030",
    price: 15199,
    compare_price: 21713,
    stock: 23,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/95dbeefe-8f1a-4d29-b196-5fdbae9aae25-Img-shoe.jpg?v=1785258407",
    description: "Adidas Break Start. Authentic Adidas casual. Size EUR 37.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-030",
      size: "EUR 37.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Under Armour Charged Escape 3",
    brand: "Under Armour",
    category: "Sports Shoes",
    sku: "TF-SHOE-031",
    price: 7599,
    compare_price: 10132,
    stock: 24,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/ab141a1b-40bc-4806-bf36-5a22da85f39f-861520-1.jpg?v=1785258394",
    description: "Under Armour Charged Escape 3. Authentic Under Armour sports. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-031",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Under Armour",
    },
  }),
  shoeProduct({
    name: "Adidas Terrex Two Ultra Primeblue",
    brand: "Adidas",
    category: "Boots",
    sku: "TF-SHOE-032",
    price: 15199,
    compare_price: 21110,
    stock: 25,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/ddd0c67f-dc33-4ca1-a7fd-50d8579a6e0a-861533-1.jpg?v=1785258369",
    description: "Adidas Terrex Two Ultra Primeblue. Authentic Adidas boot. Size EUR 38. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-032",
      size: "EUR 38",
      color: "Multi",
      material: "Mixed",
      style: "Boot",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Avia Memory Foam",
    brand: "Avia",
    category: "Orthopedic",
    sku: "TF-SHOE-033",
    price: 4099,
    compare_price: 5465,
    stock: 26,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/9a77e538-1cbb-4b25-8432-e9aec8a77773-Img-shoe.jpg?v=1785258356",
    description: "Avia Memory Foam. Authentic Avia orthopedic. Size EUR 38. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-033",
      size: "EUR 38",
      color: "Multi",
      material: "Mixed",
      style: "Orthopedic",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Avia",
    },
  }),
  shoeProduct({
    name: "Nike Tanjun",
    brand: "Nike",
    category: "Casual",
    sku: "TF-SHOE-034",
    price: 6199,
    compare_price: 8265,
    stock: 27,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/c8524ffb-456a-4c04-8c58-5cbd4976c57d-861537-1.jpg?v=1785258343",
    description: "Nike Tanjun. Authentic Nike casual. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-034",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Under Armour Hovr Sonic 4 Cn",
    brand: "Under Armour",
    category: "Casual",
    sku: "TF-SHOE-035",
    price: 18999,
    compare_price: 26388,
    stock: 28,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/551bb6d4-948e-4cda-ac9b-d125d60f39c6-861550-1.jpg?v=1785258331",
    description: "Under Armour Hovr Sonic 4 Cn. Authentic Under Armour casual. Size EUR 47.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-035",
      size: "EUR 47.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Under Armour",
    },
  }),
  shoeProduct({
    name: "Adidas Cloudfoam QT Racer",
    brand: "Adidas",
    category: "Sports Shoes",
    sku: "TF-SHOE-036",
    price: 11599,
    compare_price: 16110,
    stock: 29,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/f237364c-b949-4712-8111-1233a3482d84-861557-1.jpg?v=1785258318",
    description: "Adidas Cloudfoam QT Racer. Authentic Adidas sports. Size EUR 38. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-036",
      size: "EUR 38",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "women",
      condition: "premium",
      sourcing: "imported",
      brand: "Adidas",
    },
  }),
  shoeProduct({
    name: "Brooks Adrenaline Gts 23",
    brand: "Brooks",
    category: "Sports Shoes",
    sku: "TF-SHOE-037",
    price: 14199,
    compare_price: 18932,
    stock: 12,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/69f87f70-9c0c-44a6-9aa2-88083ec20b79-Img-shoe.jpg?v=1785258305",
    description: "Brooks Adrenaline Gts 23. Authentic Brooks sports. Size EUR 41. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-037",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Brooks",
    },
  }),
  shoeProduct({
    name: "ASICS Gel-venture 8",
    brand: "Asics",
    category: "Sports Shoes",
    sku: "TF-SHOE-038",
    price: 7099,
    compare_price: 9465,
    stock: 13,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/e339dd45-2b2d-4755-a13c-f9c2737bb21f-861560-1.jpg?v=1785258292",
    description: "ASICS Gel-venture 8. Authentic Asics sports. Size EUR 41.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-038",
      size: "EUR 41.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Asics",
    },
  }),
  shoeProduct({
    name: "Varsity Vibe",
    brand: "Varsity Vibe",
    category: "Casual",
    sku: "TF-SHOE-039",
    price: 6599,
    compare_price: 8799,
    stock: 14,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/cc98679f-0c33-4cc3-bebd-e3fb81fa8293-861561-1.jpg?v=1785258279",
    description: "Varsity Vibe. Authentic Varsity Vibe casual. Size EUR 39. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-039",
      size: "EUR 39",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Varsity Vibe",
    },
  }),
  shoeProduct({
    name: "Under Armour Thrill 2",
    brand: "Under Armour",
    category: "Casual",
    sku: "TF-SHOE-040",
    price: 7699,
    compare_price: 10265,
    stock: 15,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/d825fbd6-65a4-4eac-9650-f38bff000013-Img-shoe.jpg?v=1785258266",
    description: "Under Armour Thrill 2. Authentic Under Armour casual. Size EUR 39. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-040",
      size: "EUR 39",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Under Armour",
    },
  }),
  shoeProduct({
    name: "Nike Team Hustle D 10",
    brand: "Nike",
    category: "Kids Shoes",
    sku: "TF-SHOE-041",
    price: 16199,
    compare_price: 23141,
    stock: 16,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/54446bdf-7c1a-4eb0-8d7e-7202c22ffe6a-861566-1.jpg?v=1785258253",
    description: "Nike Team Hustle D 10. Authentic Nike casual. Size EUR 37.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-041",
      size: "EUR 37.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "kids",
      condition: "premium",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Puma Pacer Future",
    brand: "Puma",
    category: "Casual",
    sku: "TF-SHOE-042",
    price: 8399,
    compare_price: 11199,
    stock: 17,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/cfcc92da-68bc-40d8-95b8-9989ec56ce38-861567-1.jpg?v=1785258240",
    description: "Puma Pacer Future. Authentic Puma casual. Size EUR 39. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-042",
      size: "EUR 39",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Puma",
    },
  }),
  shoeProduct({
    name: "Under Armour Charged Bandit 3",
    brand: "Under Armour",
    category: "Sports Shoes",
    sku: "TF-SHOE-043",
    price: 8699,
    compare_price: 11599,
    stock: 18,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/69371dd3-3114-43b2-ae59-130a25cc9912-861571-1.jpg?v=1785258227",
    description: "Under Armour Charged Bandit 3. Authentic Under Armour sports. Size EUR 37.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-043",
      size: "EUR 37.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Under Armour",
    },
  }),
  shoeProduct({
    name: "New Balance 574",
    brand: "New Balance",
    category: "Casual",
    sku: "TF-SHOE-044",
    price: 7399,
    compare_price: 9865,
    stock: 19,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/1c814ec7-d85d-4cfa-a824-f42afae94580-861580-1.jpg?v=1785258213",
    description: "New Balance 574. Authentic New Balance casual. Size EUR 41.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-044",
      size: "EUR 41.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Jordan 6 Rings",
    brand: "Jordan",
    category: "Casual",
    sku: "TF-SHOE-045",
    price: 9499,
    compare_price: 12665,
    stock: 20,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/761a65a3-4e62-4bb6-b08b-a797df19bd03-Img-shoe.jpg?v=1785258200",
    description: "Jordan 6 Rings. Authentic Jordan casual. Size EUR 38.5. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-045",
      size: "EUR 38.5",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Jordan",
    },
  }),
  shoeProduct({
    name: "New Balance Fuelcore Nergize",
    brand: "New Balance",
    category: "Women's Shoes",
    sku: "TF-SHOE-046",
    price: 7699,
    compare_price: 10265,
    stock: 21,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/c64c407b-fce6-4cf2-8231-0733e3843ed1-861597-1.jpg?v=1785258187",
    description: "New Balance Fuelcore Nergize. Authentic New Balance casual. Size EUR 38. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-046",
      size: "EUR 38",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "women",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Skechers Slip-ins: Gorun Consistent 2.0 - Endure",
    brand: "Skechers",
    category: "Sports Shoes",
    sku: "TF-SHOE-047",
    price: 8499,
    compare_price: 11332,
    stock: 22,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/8558085d-1a23-4ff8-beaa-c789b74ddc42-Img-shoe.jpg?v=1785258175",
    description: "Skechers Slip-ins: Gorun Consistent 2.0 - Endure. Authentic Skechers sports. Size EUR 39.5. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-047",
      size: "EUR 39.5",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Skechers",
    },
  }),
  shoeProduct({
    name: "New Balance 574",
    brand: "New Balance",
    category: "Casual",
    sku: "TF-SHOE-048",
    price: 8099,
    compare_price: 10799,
    stock: 23,
    featured: false,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/5093612d-890e-47fe-b69e-0fec5942a5e5-Img-shoe.jpg?v=1785258162",
    description: "New Balance 574. Authentic New Balance casual. Size EUR 39. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-048",
      size: "EUR 39",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "New Balance",
    },
  }),
  shoeProduct({
    name: "Nike Reax Run 5",
    brand: "Nike",
    category: "Sports Shoes",
    sku: "TF-SHOE-049",
    price: 11799,
    compare_price: 15732,
    stock: 24,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/b47ff3ba-4b50-485d-881b-c62e7ce0b26f-Img-shoe.jpg?v=1785258149",
    description: "Nike Reax Run 5. Authentic Nike sports. Size EUR 36. Graded excellent. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-049",
      size: "EUR 36",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "excellent",
      sourcing: "imported",
      brand: "Nike",
    },
  }),
  shoeProduct({
    name: "Brooks Glycerin 19",
    brand: "Brooks",
    category: "Sports Shoes",
    sku: "TF-SHOE-050",
    price: 9299,
    compare_price: 12399,
    stock: 25,
    featured: true,
    image: "https://cdn.shopify.com/s/files/1/1692/9471/files/1ed225a2-3e88-4654-bc70-e4a0ebd09433-861613-1.jpg?v=1785258137",
    description: "Brooks Glycerin 19. Authentic Brooks sports. Size EUR 41. Graded premium. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-050",
      size: "EUR 41",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "unisex",
      condition: "premium",
      sourcing: "imported",
      brand: "Brooks",
    },
  }),
  shoeProduct({
    name: "Bata Men's Formal Oxford",
    brand: "Bata Pakistan",
    category: "Men's Shoes",
    sku: "TF-SHOE-051",
    price: 4500,
    compare_price: 5625,
    stock: 26,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1920,c_limit/e0c4b82b-402e-4b9b-aa47-297e1e48ecc4/nike-just-do-it.jpg",
    description: "Bata Men's Formal Oxford. Authentic Bata Pakistan formal. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-051",
      size: "41",
      color: "Multi",
      material: "Genuine Leather",
      style: "Formal",
      gender: "men",
      condition: "new",
      sourcing: "local",
      brand: "Bata Pakistan",
    },
  }),
  shoeProduct({
    name: "Service Women's Block Heel",
    brand: "Service Shoes",
    category: "Women's Shoes",
    sku: "TF-SHOE-052",
    price: 3800,
    compare_price: 4750,
    stock: 27,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/0d85b6c4-8205-4703-bf22-686d3c7d9580/nike-just-do-it.jpg",
    description: "Service Women's Block Heel. Authentic Service Shoes formal. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-052",
      size: "41",
      color: "Multi",
      material: "Genuine Leather",
      style: "Formal",
      gender: "women",
      condition: "new",
      sourcing: "local",
      brand: "Service Shoes",
    },
  }),
  shoeProduct({
    name: "Borjan Casual Loafer",
    brand: "Borjan",
    category: "Men's Shoes",
    sku: "TF-SHOE-053",
    price: 5200,
    compare_price: 6500,
    stock: 28,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/0662d560-32e8-4625-afe7-084f3654ce61/nike-just-do-it.jpg",
    description: "Borjan Casual Loafer. Authentic Borjan casual. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-053",
      size: "41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "men",
      condition: "new",
      sourcing: "local",
      brand: "Borjan",
    },
  }),
  shoeProduct({
    name: "Stylo Kids Canvas Sneaker",
    brand: "Stylo",
    category: "Kids Shoes",
    sku: "TF-SHOE-054",
    price: 2200,
    compare_price: 2750,
    stock: 29,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1920,c_limit/7fc4e072-3654-4303-9fb9-dbb0a81a9a8f/nike-just-do-it.jpg",
    description: "Stylo Kids Canvas Sneaker. Authentic Stylo casual. Size 32. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-054",
      size: "32",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "kids",
      condition: "new",
      sourcing: "local",
      brand: "Stylo",
    },
  }),
  shoeProduct({
    name: "Metro Soft Walk Orthopedic",
    brand: "Metro Shoes",
    category: "Orthopedic",
    sku: "TF-SHOE-055",
    price: 6100,
    compare_price: 7625,
    stock: 12,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/498fd98b-9840-450b-9f8d-ec0b6fe6f71d/nike-just-do-it.jpg",
    description: "Metro Soft Walk Orthopedic. Authentic Metro Shoes orthopedic. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-055",
      size: "41",
      color: "Multi",
      material: "Mixed",
      style: "Orthopedic",
      gender: "unisex",
      condition: "new",
      sourcing: "local",
      brand: "Metro Shoes",
    },
  }),
  shoeProduct({
    name: "Ndure Sports Runner",
    brand: "Ndure",
    category: "Sports Shoes",
    sku: "TF-SHOE-056",
    price: 4900,
    compare_price: 6125,
    stock: 13,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1920,c_limit/266ec8a0-9016-40e4-bf49-84b3589b8060/nike-just-do-it.jpg",
    description: "Ndure Sports Runner. Authentic Ndure sports. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-056",
      size: "41",
      color: "Multi",
      material: "Mixed",
      style: "Sports",
      gender: "men",
      condition: "new",
      sourcing: "local",
      brand: "Ndure",
    },
  }),
  shoeProduct({
    name: "ECS Everyday Slip-On",
    brand: "ECS",
    category: "Casual",
    sku: "TF-SHOE-057",
    price: 3400,
    compare_price: 4250,
    stock: 14,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/b3fa2b43-b73c-4c8a-af70-ea7733be2df2/nike-just-do-it.jpg",
    description: "ECS Everyday Slip-On. Authentic ECS casual. Size 41. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-057",
      size: "41",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "unisex",
      condition: "new",
      sourcing: "local",
      brand: "ECS",
    },
  }),
  shoeProduct({
    name: "Servis Cheetah School Shoe",
    brand: "Servis Cheetah",
    category: "Kids Shoes",
    sku: "TF-SHOE-058",
    price: 2800,
    compare_price: 3500,
    stock: 15,
    featured: false,
    image: "https://static.nike.com/a/images/f_auto,cs_srgb/w_1920,c_limit/d949f14a-1bd6-4cd1-b03c-810894802ec9/nike-just-do-it.jpg",
    description: "Servis Cheetah School Shoe. Authentic Servis Cheetah casual. Size 32. Brand new local line. Clear sizing and nationwide delivery.",
    domain_data: {
      articlenumber: "TF-SHOE-058",
      size: "32",
      color: "Multi",
      material: "Mixed",
      style: "Casual",
      gender: "kids",
      condition: "new",
      sourcing: "local",
      brand: "Servis Cheetah",
    },
  }),
];

export default FOOTWEAR_SEED_PRODUCTS;
