/**
 * Tenvo Marine curated demo catalog — DWG taxonomy + OEM-style SKUs.
 * Media from archive/ships-parts.html (see shipsArchiveExtract.json).
 */

const CDN = 'https://c11cbcde.delivery.rocketcdn.me/wp-content/uploads';

/** @type {string[]} */
export const MARINE_PARTS_SEED_CATEGORIES = [
  'New Systems',
  'Used Systems',
  'Spare Parts',
  'Repair Service',
  'Rudder Propellers',
  'Tunnel Thrusters',
  'Azimuth Drives',
  'Seals & Sterntubes',
  'Steering & Rudders',
  'Hydraulic Cranes',
];

const FAMILY_IMAGE = {
  'Hydraulic retractable rudder propeller': `${CDN}/2025/10/Hydraulic-retractable-rudder-propellers-1.png`,
  'Well-mounted rudder propeller': `${CDN}/2025/10/Hydraulic-well-mounted-rudder-propellers-1.png`,
  'Tunnel thruster': `${CDN}/2025/10/Hydraulic-tunnel-thruster-electric-kleiner.png`,
  'Azimuth L/Z-drive': `${CDN}/2025/10/L-Drive-and-Z-Drive-azimuth-deckmounted-navigators.png`,
  'Pump-jet / waterjet': `${CDN}/2025/10/Used-Pump-jets-waterjets.png`,
  'Hydraulic crane': `${CDN}/2025/10/Hydraulic-Cranes.png`,
  'Sterntube / shaft seal': `${CDN}/2025/10/Sterntube-Compact-and-Shaft-Seals.png`,
};

function img(equipmentType, fallback) {
  return FAMILY_IMAGE[equipmentType] || fallback || `${CDN}/2026/02/Spare-Parts.jpg`;
}

/**
 * @param {Omit<Record<string, unknown>, never>} row
 */
function sku(row) {
  return {
    unit: 'pcs',
    is_featured: false,
    imageCredit: 'DWG Trading archive (ships-parts.html)',
    ...row,
    domain_data: {
      partnumber: row.sku,
      oemnumber: row.oemnumber,
      interchangecode: row.interchangecode || '',
      equipmenttype: row.equipmenttype,
      systemcondition: row.systemcondition,
      vesseltype: row.vesseltype || 'Workboat',
      manufacturer: row.manufacturer || 'Generic / Aftermarket',
      criticality: row.criticality || 'B - Important',
      warrantyperiod: row.warrantyperiod || '1 Year',
      compatiblemodels: row.compatiblemodels || '',
    },
  };
}

/** @type {Array<Record<string, unknown>>} */
export const MARINE_PARTS_SEED_CATALOG = [
  sku({
    name: 'Hydraulic Retractable Rudder Propeller SRP-1215',
    brand: 'Schottel',
    category: 'Rudder Propellers',
    unit: 'set',
    price: 185000,
    compare_price: 210000,
    cost_price: 142000,
    stock: 2,
    sku: 'TM-SRP-1215-N',
    oemnumber: 'SRP-1215',
    equipmenttype: 'Hydraulic retractable rudder propeller',
    systemcondition: 'new',
    vesseltype: 'Tug',
    manufacturer: 'Schottel',
    criticality: 'A - Critical',
    warrantyperiod: '2 Years',
    compatiblemodels: 'SRP 1215 | SRP 1212',
    description: 'Complete new hydraulic retractable rudder propeller for harbour tugs and workboats.',
    image_url: img('Hydraulic retractable rudder propeller'),
    is_featured: true,
  }),
  sku({
    name: 'Hydraulic Retractable Rudder Propeller SRP-1010 Used',
    brand: 'Schottel',
    category: 'Used Systems',
    unit: 'set',
    price: 78000,
    compare_price: 95000,
    cost_price: 52000,
    stock: 1,
    sku: 'TM-SRP-1010-U',
    oemnumber: 'SRP-1010',
    equipmenttype: 'Hydraulic retractable rudder propeller',
    systemcondition: 'used',
    vesseltype: 'Workboat',
    manufacturer: 'Schottel',
    criticality: 'A - Critical',
    warrantyperiod: '6 Months',
    compatiblemodels: 'SRP 1010',
    description: 'Inspected used retractable rudder propeller with service history pack.',
    image_url: img('Hydraulic retractable rudder propeller', `${CDN}/2025/10/Used-Rudder-Proppelers.png`),
    is_featured: true,
  }),
  sku({
    name: 'Well-Mounted Rudder Propeller WM-850',
    brand: 'Veth',
    category: 'New Systems',
    unit: 'set',
    price: 142000,
    cost_price: 110000,
    stock: 1,
    sku: 'TM-WM-850-N',
    oemnumber: 'VETH-WM-850',
    equipmenttype: 'Well-mounted rudder propeller',
    systemcondition: 'new',
    vesseltype: 'Ferry',
    manufacturer: 'Veth',
    criticality: 'A - Critical',
    warrantyperiod: 'OEM Standard',
    compatiblemodels: 'WM-850 | WM-800',
    description: 'New well-mounted rudder propeller package with hydraulic power unit interface.',
    image_url: img('Well-mounted rudder propeller'),
    is_featured: true,
  }),
  sku({
    name: 'Tunnel Thruster TT-1650 Hydraulic',
    brand: 'Wärtsilä',
    category: 'Tunnel Thrusters',
    unit: 'set',
    price: 98000,
    compare_price: 112000,
    cost_price: 74000,
    stock: 2,
    sku: 'TM-TT-1650-N',
    oemnumber: 'TT-1650-H',
    equipmenttype: 'Tunnel thruster',
    systemcondition: 'new',
    vesseltype: 'Cargo',
    manufacturer: 'Wärtsilä',
    criticality: 'A - Critical',
    warrantyperiod: '2 Years',
    compatiblemodels: 'TT 1650 | CT 165',
    description: 'Hydraulic tunnel thruster unit for mid-size cargo and tanker vessels.',
    image_url: img('Tunnel thruster'),
    is_featured: true,
  }),
  sku({
    name: 'Electric Tunnel Thruster ET-1200',
    brand: 'Kongsberg',
    category: 'Tunnel Thrusters',
    unit: 'set',
    price: 87500,
    cost_price: 66000,
    stock: 1,
    sku: 'TM-ET-1200-N',
    oemnumber: 'KM-ET-1200',
    equipmenttype: 'Tunnel thruster',
    systemcondition: 'new',
    vesseltype: 'Ferry',
    manufacturer: 'Kongsberg',
    criticality: 'A - Critical',
    warrantyperiod: 'OEM Standard',
    compatiblemodels: 'ET-1200',
    description: 'Electric / mechanical tunnel thruster with control interface harness.',
    image_url: `${CDN}/2025/10/Electric-Mechanical-Tunnel-Thrusters.png`,
  }),
  sku({
    name: 'Azimuth L-Drive Deck Navigator AZ-450',
    brand: 'ZF',
    category: 'Azimuth Drives',
    unit: 'set',
    price: 156000,
    cost_price: 118000,
    stock: 1,
    sku: 'TM-AZ-450-N',
    oemnumber: 'ZF-AZ-450',
    equipmenttype: 'Azimuth L/Z-drive',
    systemcondition: 'new',
    vesseltype: 'Workboat',
    manufacturer: 'ZF',
    criticality: 'A - Critical',
    warrantyperiod: '2 Years',
    compatiblemodels: 'AZ-450 | AZ-440',
    description: 'L-drive azimuth deckmounted navigator for workboat propulsion.',
    image_url: img('Azimuth L/Z-drive'),
    is_featured: true,
  }),
  sku({
    name: 'Azimuth Z-Drive AZ-380 Refurbished',
    brand: 'ZF',
    category: 'Used Systems',
    unit: 'set',
    price: 92000,
    cost_price: 61000,
    stock: 1,
    sku: 'TM-AZ-380-R',
    oemnumber: 'ZF-AZ-380',
    equipmenttype: 'Azimuth L/Z-drive',
    systemcondition: 'refurbished',
    vesseltype: 'Tug',
    manufacturer: 'ZF',
    criticality: 'A - Critical',
    warrantyperiod: '1 Year',
    compatiblemodels: 'AZ-380',
    description: 'Workshop-refurbished Z-drive with new seals and load-tested gearbox.',
    image_url: img('Azimuth L/Z-drive'),
  }),
  sku({
    name: 'Pump-Jet Waterjet PJ-220 Used',
    brand: 'DWG',
    category: 'Used Systems',
    unit: 'set',
    price: 64000,
    cost_price: 41000,
    stock: 1,
    sku: 'TM-PJ-220-U',
    oemnumber: 'PJ-220',
    equipmenttype: 'Pump-jet / waterjet',
    systemcondition: 'used',
    vesseltype: 'Workboat',
    manufacturer: 'DWG',
    criticality: 'B - Important',
    warrantyperiod: '3 Months',
    compatiblemodels: 'PJ-220 | PJ-200',
    description: 'Used pump-jet / waterjet assembly, inspected impeller and intake.',
    image_url: img('Pump-jet / waterjet'),
  }),
  sku({
    name: 'Hydraulic Deck Crane HC-12T',
    brand: 'DWG',
    category: 'Hydraulic Cranes',
    unit: 'set',
    price: 54000,
    cost_price: 39000,
    stock: 2,
    sku: 'TM-HC-12T-N',
    oemnumber: 'HC-12T',
    equipmenttype: 'Hydraulic crane',
    systemcondition: 'new',
    vesseltype: 'Workboat',
    manufacturer: 'DWG',
    criticality: 'B - Important',
    warrantyperiod: '1 Year',
    compatiblemodels: 'HC-12T',
    description: '12-tonne hydraulic deck crane package for workboats and supply vessels.',
    image_url: img('Hydraulic crane'),
    is_featured: true,
  }),
  sku({
    name: 'Steering Gear Rotary Vane SG-RV40',
    brand: 'Neuver / Tenfjord',
    category: 'Steering & Rudders',
    unit: 'set',
    price: 72000,
    cost_price: 54000,
    stock: 1,
    sku: 'TM-SG-RV40-N',
    oemnumber: 'TF-RV40',
    equipmenttype: 'Steering gear',
    systemcondition: 'new',
    vesseltype: 'Tanker',
    manufacturer: 'Neuver / Tenfjord',
    criticality: 'A - Critical',
    warrantyperiod: 'OEM Standard',
    compatiblemodels: 'RV40 | Tenfjord RV',
    description: 'Rotary vane steering gear system for commercial tankers.',
    image_url: `${CDN}/2025/08/New-systems-home.jpg`,
    is_featured: true,
  }),
  sku({
    name: 'Flap Rudder FR-2800',
    brand: 'Frydenbø',
    category: 'Steering & Rudders',
    unit: 'pcs',
    price: 48000,
    cost_price: 35000,
    stock: 1,
    sku: 'TM-FR-2800-N',
    oemnumber: 'FB-FR-2800',
    equipmenttype: 'Rudder',
    systemcondition: 'new',
    vesseltype: 'Cargo',
    manufacturer: 'Frydenbø',
    criticality: 'A - Critical',
    warrantyperiod: 'OEM Standard',
    compatiblemodels: 'FR-2800',
    description: 'Optimized flap rudder for cargo vessels requiring high maneuverability.',
    image_url: `${CDN}/2025/03/Home-topfoto-dwg-trading.jpg`,
  }),
  // Spare kits & seals
  sku({
    name: 'Tunnel Thruster Seal Kit TT-1650',
    brand: 'Wärtsilä',
    category: 'Spare Parts',
    unit: 'kit',
    price: 4200,
    compare_price: 4800,
    cost_price: 2600,
    stock: 12,
    sku: 'TM-TT-1650-SK',
    oemnumber: 'OEM-TT-1650-SK',
    interchangecode: 'TT1650-SEAL-KIT',
    equipmenttype: 'Tunnel thruster',
    systemcondition: 'spare',
    vesseltype: 'Cargo',
    manufacturer: 'Wärtsilä',
    criticality: 'A - Critical',
    warrantyperiod: '6 Months',
    compatiblemodels: 'TT 1650',
    description: 'OEM-compatible seal kit for hydraulic tunnel thrusters.',
    image_url: img('Tunnel thruster', `${CDN}/2026/02/Spare-Parts.jpg`),
    is_featured: true,
  }),
  sku({
    name: 'Sterntube Compact Seal Set ST-CS220',
    brand: 'Generic / Aftermarket',
    category: 'Seals & Sterntubes',
    unit: 'set',
    price: 6800,
    cost_price: 4100,
    stock: 8,
    sku: 'TM-ST-CS220',
    oemnumber: 'ST-CS220',
    interchangecode: 'COMPACT-220',
    equipmenttype: 'Sterntube / shaft seal',
    systemcondition: 'spare',
    vesseltype: 'Ferry',
    manufacturer: 'Generic / Aftermarket',
    criticality: 'A - Critical',
    warrantyperiod: '1 Year',
    compatiblemodels: 'CS220 | Compact 220',
    description: 'Compact sterntube and shaft seal set for mid-size vessels.',
    image_url: img('Sterntube / shaft seal'),
    is_featured: true,
  }),
  sku({
    name: 'Rudder Propeller Seal Kit SRP-1215',
    brand: 'Schottel',
    category: 'Spare Parts',
    unit: 'kit',
    price: 5600,
    cost_price: 3400,
    stock: 10,
    sku: 'TM-SRP-1215-SK',
    oemnumber: 'SRP-1215-SK',
    equipmenttype: 'Hydraulic retractable rudder propeller',
    systemcondition: 'spare',
    vesseltype: 'Tug',
    manufacturer: 'Schottel',
    criticality: 'A - Critical',
    warrantyperiod: '6 Months',
    compatiblemodels: 'SRP 1215',
    description: 'Complete seal kit for SRP-class rudder propellers.',
    image_url: `${CDN}/2025/10/Spare-partes-rudder-propppelers.png`,
  }),
  sku({
    name: 'Azimuth Gearbox Oil Filter AZ-450',
    brand: 'ZF',
    category: 'Spare Parts',
    unit: 'pcs',
    price: 185,
    cost_price: 95,
    stock: 40,
    sku: 'TM-AZ-450-OF',
    oemnumber: 'ZF-AZ-450-OF',
    equipmenttype: 'Azimuth L/Z-drive',
    systemcondition: 'spare',
    vesseltype: 'Workboat',
    manufacturer: 'ZF',
    criticality: 'C - General',
    warrantyperiod: 'No Warranty',
    compatiblemodels: 'AZ-450',
    description: 'Gearbox oil filter element for AZ-450 azimuth drives.',
    image_url: `${CDN}/2026/02/Spare-Parts.jpg`,
  }),
  sku({
    name: 'Hydraulic Pump Cartridge HP-63',
    brand: 'DWG',
    category: 'Spare Parts',
    unit: 'pcs',
    price: 3200,
    cost_price: 1900,
    stock: 6,
    sku: 'TM-HP-63-C',
    oemnumber: 'HP-63-CART',
    equipmenttype: 'Hydraulic crane',
    systemcondition: 'spare',
    vesseltype: 'Workboat',
    manufacturer: 'DWG',
    criticality: 'B - Important',
    warrantyperiod: '6 Months',
    compatiblemodels: 'HC-12T | HP-63',
    description: 'Hydraulic pump cartridge for deck crane power packs.',
    image_url: img('Hydraulic crane', `${CDN}/2026/02/Spare-Parts.jpg`),
  }),
  sku({
    name: 'Thruster Propeller Blade Set TT-1650',
    brand: 'Wärtsilä',
    category: 'Spare Parts',
    unit: 'set',
    price: 12400,
    cost_price: 8200,
    stock: 3,
    sku: 'TM-TT-1650-BL',
    oemnumber: 'TT-1650-BLADE',
    equipmenttype: 'Tunnel thruster',
    systemcondition: 'spare',
    vesseltype: 'Tanker',
    manufacturer: 'Wärtsilä',
    criticality: 'A - Critical',
    warrantyperiod: '1 Year',
    compatiblemodels: 'TT 1650',
    description: 'Matched propeller blade set for TT-1650 tunnel thrusters.',
    image_url: img('Tunnel thruster'),
  }),
  sku({
    name: 'Shaft Seal Face Ring SS-F180',
    brand: 'Generic / Aftermarket',
    category: 'Seals & Sterntubes',
    unit: 'pcs',
    price: 980,
    cost_price: 540,
    stock: 18,
    sku: 'TM-SS-F180',
    oemnumber: 'SS-F180',
    interchangecode: 'FACE-180',
    equipmenttype: 'Sterntube / shaft seal',
    systemcondition: 'spare',
    vesseltype: 'Cargo',
    manufacturer: 'Generic / Aftermarket',
    criticality: 'B - Important',
    warrantyperiod: '3 Months',
    compatiblemodels: 'CS220 | F180',
    description: 'Replaceable face ring for compact shaft seal assemblies.',
    image_url: img('Sterntube / shaft seal'),
  }),
  sku({
    name: 'Steering Gear Seal Kit SG-RV40',
    brand: 'Neuver / Tenfjord',
    category: 'Spare Parts',
    unit: 'kit',
    price: 2750,
    cost_price: 1600,
    stock: 7,
    sku: 'TM-SG-RV40-SK',
    oemnumber: 'TF-RV40-SK',
    equipmenttype: 'Steering gear',
    systemcondition: 'spare',
    vesseltype: 'Tanker',
    manufacturer: 'Neuver / Tenfjord',
    criticality: 'A - Critical',
    warrantyperiod: '6 Months',
    compatiblemodels: 'RV40',
    description: 'Seal kit for rotary vane steering gear overhaul.',
    image_url: `${CDN}/2026/02/Spare-Parts.jpg`,
  }),
  sku({
    name: 'Rudder Stock Bearing Bush RB-320',
    brand: 'Frydenbø',
    category: 'Spare Parts',
    unit: 'pcs',
    price: 4100,
    cost_price: 2500,
    stock: 4,
    sku: 'TM-RB-320',
    oemnumber: 'FB-RB-320',
    equipmenttype: 'Rudder',
    systemcondition: 'spare',
    vesseltype: 'Cargo',
    manufacturer: 'Frydenbø',
    criticality: 'B - Important',
    warrantyperiod: '1 Year',
    compatiblemodels: 'FR-2800 | RB-320',
    description: 'Rudder stock bearing bush for flap and classic rudders.',
    image_url: `${CDN}/2026/02/Spare-Parts.jpg`,
  }),
];

// Generate additional spare/consumable SKUs for catalogue depth
const SPARE_TEMPLATES = [
  { prefix: 'FILTER', name: 'Hydraulic Return Filter', price: 145, cost: 70, cat: 'Spare Parts', eq: 'Hydraulic crane', crit: 'C - General' },
  { prefix: 'HOSE', name: 'High-Pressure Hose Assembly', price: 320, cost: 160, cat: 'Spare Parts', eq: 'Hydraulic retractable rudder propeller', crit: 'B - Important' },
  { prefix: 'COUPL', name: 'Quick Coupling Pair', price: 95, cost: 45, cat: 'Spare Parts', eq: 'Hydraulic crane', crit: 'C - General' },
  { prefix: 'GASK', name: 'Gearbox Cover Gasket', price: 68, cost: 28, cat: 'Spare Parts', eq: 'Azimuth L/Z-drive', crit: 'C - General' },
  { prefix: 'BRG', name: 'Thruster Shaft Bearing', price: 1850, cost: 980, cat: 'Spare Parts', eq: 'Tunnel thruster', crit: 'A - Critical' },
  { prefix: 'ORING', name: 'O-Ring Kit Metric Assortment', price: 55, cost: 22, cat: 'Spare Parts', eq: 'Other', crit: 'C - General' },
  { prefix: 'SENSOR', name: 'Angle Feedback Sensor', price: 740, cost: 390, cat: 'Spare Parts', eq: 'Steering gear', crit: 'B - Important' },
  { prefix: 'VALVE', name: 'Proportional Control Valve', price: 2100, cost: 1250, cat: 'Spare Parts', eq: 'Hydraulic retractable rudder propeller', crit: 'A - Critical' },
  { prefix: 'IMPELL', name: 'Waterjet Impeller', price: 5400, cost: 3100, cat: 'Spare Parts', eq: 'Pump-jet / waterjet', crit: 'A - Critical' },
  { prefix: 'ANODE', name: 'Sacrificial Anode Set', price: 210, cost: 95, cat: 'Spare Parts', eq: 'Tunnel thruster', crit: 'C - General' },
];

const VESSELS = ['Workboat', 'Tug', 'Ferry', 'Tanker', 'Cargo', 'Yacht'];
const MAKERS = ['Wärtsilä', 'Schottel', 'Kongsberg', 'Veth', 'ZF', 'DWG', 'Generic / Aftermarket'];

for (let i = 0; i < SPARE_TEMPLATES.length; i++) {
  const t = SPARE_TEMPLATES[i];
  for (let n = 1; n <= 4; n++) {
    const id = `${t.prefix}-${String(100 + i * 4 + n).padStart(3, '0')}`;
    MARINE_PARTS_SEED_CATALOG.push(
      sku({
        name: `${t.name} ${id}`,
        brand: MAKERS[n % MAKERS.length],
        category: t.cat,
        unit: n % 3 === 0 ? 'kit' : 'pcs',
        price: t.price * (1 + (n - 1) * 0.12),
        cost_price: t.cost * (1 + (n - 1) * 0.1),
        stock: 8 + n * 3,
        sku: `TM-${id}`,
        oemnumber: `OEM-${id}`,
        interchangecode: `XR-${id}`,
        equipmenttype: t.eq,
        systemcondition: 'spare',
        vesseltype: VESSELS[(i + n) % VESSELS.length],
        manufacturer: MAKERS[n % MAKERS.length],
        criticality: t.crit,
        warrantyperiod: t.crit.startsWith('A') ? '6 Months' : 'No Warranty',
        compatiblemodels: id,
        description: `${t.name} for marine propulsion and deck systems. Catalogue part ${id}.`,
        image_url: `${CDN}/2026/02/Spare-Parts.jpg`,
        is_featured: n === 1 && i < 3,
      })
    );
  }
}

export const MARINE_PARTS_SEED_META = {
  source: 'archive/ships-parts.html',
  origin: 'https://dwgtrading.com/',
  count: MARINE_PARTS_SEED_CATALOG.length,
};
