/**
 * Tenvo Milk Demo / milk-shop registration catalog.
 * Built from scraped platforms (Bismillah foodpanda archive, Punjab Milk Shop, Pure Nest)
 * plus curated kg-first PK doodh-shop essentials.
 *
 * Regenerate: node scripts/fetch-milk-shop-catalog.mjs && node scripts/build-milk-shop-seed-catalog.mjs
 */
import { buildUnsplashImageUrl } from '../storefront/unsplashUrl.js';

/** Stable Unsplash photo ids (allowlisted dairy / bakery / beverage pools). */
const P = {
  "milk": "1563636619-e9143da7973b",
  "yogurt": "1488477181946-6428a0291777",
  "aisle": "1578916171728-46686eac8d58",
  "bread": "1509440159596-0249088772ff",
  "bread2": "1549931319-a545dcf3bc73",
  "drink": "1544145945-f90425340c7e",
  "drink2": "1437418747212-8d9709afab22",
  "produce": "1542838132-92c53300491e"
};

/** @param {string} photoId */
function img(photoId) {
  return buildUnsplashImageUrl(photoId, { w: 800, q: 82 });
}

export const MILK_SHOP_SEED_CATEGORIES = [
  "Fresh Milk",
  "Yogurt / Dahi",
  "Cream & Butter",
  "Ghee",
  "Cheese & Khoya",
  "Lassi & Drinks",
  "Dairy Sweets",
  "Packaged Dairy",
  "Eggs",
  "Bakery Staples"
];

export const MILK_SHOP_MARKETING_HERO_IMAGE = img(P.milk);

/**
 * @param {object} partial
 * @returns {Record<string, unknown>}
 */
function milkProduct(partial) {
  const {
    name,
    brand = 'Tenvo Milk',
    category,
    sku,
    price,
    compare_price,
    unit = 'kg',
    stock = 80,
    featured = false,
    image,
    description,
    domain_data = {},
  } = partial;
  const cost = Math.round(Number(price) * 0.72);
  return {
    name,
    brand,
    category,
    unit,
    price,
    compare_price: compare_price ?? null,
    cost_price: cost,
    stock,
    sku,
    description:
      description ||
      `${name}. Fresh dairy from Tenvo Milk Shop. Sold ${unit === 'kg' ? 'by the kilogram' : `per ${unit}`}.`,
    image_url: image,
    imageCredit: 'Unsplash seed',
    is_featured: featured,
    domain_data: {
      source: domain_data.source || (brand === 'Tenvo Milk' ? 'Farm / Collector' : 'Brand'),
      fatpercent: domain_data.fatpercent || '',
      chill: domain_data.chill !== false,
      ...domain_data,
    },
  };
}

/** @type {Array<Record<string, unknown>>} */
export const MILK_SHOP_SEED_PRODUCTS = [
  milkProduct({
    name: "Fresh Cow Milk",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-FRESH-COW-MILK-01",
    unit: "kg",
    price: 220,
    stock: 120,
    featured: true,
    image: img(P.milk),
    description: "Farm-fresh cow milk sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com + purenest.pk","chill":true,"fatpercent":"3.5"},
  }),
  milkProduct({
    name: "Fresh Buffalo Milk",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-FRESH-BUFFALO-MILK-02",
    unit: "kg",
    price: 240,
    stock: 120,
    featured: true,
    image: img(P.milk),
    description: "Thick buffalo milk by kg.",
    domain_data: {"source":"punjabmilkshop.com + purenest.pk","chill":true,"fatpercent":"6.5"},
  }),
  milkProduct({
    name: "Fresh Goat Milk",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-FRESH-GOAT-MILK-03",
    unit: "kg",
    price: 280,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Fresh Goat Milk. Fresh dairy from Tenvo Milk Demo (sourced from purequalitymilk.com). Sold by the kilogram.",
    domain_data: {"source":"purequalitymilk.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Cow Milk (Pure Nest)",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-COW-MILK-PURE-NEST-04",
    unit: "litre",
    price: 250,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Pure Nest farm cow milk per litre.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":"3.5"},
  }),
  milkProduct({
    name: "Buffalo Milk (Pure Nest)",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-BUFFALO-MILK-PURE-NEST-05",
    unit: "litre",
    price: 260,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Buffalo Milk (Pure Nest). Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold per litre.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":"6.5"},
  }),
  milkProduct({
    name: "Homemade Dahi",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-HOMEMADE-DAHI-06",
    unit: "kg",
    price: 260,
    stock: 120,
    featured: true,
    image: img(P.yogurt),
    description: "Homemade Dahi. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Yogurt Pure & Thick",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-YOGURT-PURE-THICK-07",
    unit: "kg",
    price: 280,
    stock: 120,
    featured: false,
    image: img(P.yogurt),
    description: "Yogurt Pure & Thick. Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold by the kilogram.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Makkhan (Desi Butter)",
    brand: "Tenvo Milk",
    category: "Cream & Butter",
    sku: "MLK-FRESH-MAKKHAN-DESI-BUTTER-08",
    unit: "kg",
    price: 1800,
    stock: 120,
    featured: true,
    image: img(P.milk),
    description: "Fresh Makkhan (Desi Butter). Fresh dairy from Tenvo Milk Demo (sourced from purequalitymilk.com). Sold by the kilogram.",
    domain_data: {"source":"purequalitymilk.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Malai (Cream)",
    brand: "Tenvo Milk",
    category: "Cream & Butter",
    sku: "MLK-FRESH-MALAI-CREAM-09",
    unit: "kg",
    price: 900,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Fresh Malai (Cream). Fresh dairy from Tenvo Milk Demo (sourced from purequalitymilk.com). Sold by the kilogram.",
    domain_data: {"source":"purequalitymilk.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Desi Ghee",
    brand: "Tenvo Milk",
    category: "Ghee",
    sku: "MLK-DESI-GHEE-10",
    unit: "kg",
    price: 4000,
    stock: 120,
    featured: true,
    image: img(P.aisle),
    description: "Desi Ghee. Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold by the kilogram.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Desi Ghee 1 Kg",
    brand: "Tenvo Milk",
    category: "Ghee",
    sku: "MLK-DESI-GHEE-1-KG-11",
    unit: "kg",
    price: 3850,
    stock: 120,
    featured: true,
    image: img(P.aisle),
    description: "Desi Ghee 1 Kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Paneer",
    brand: "Tenvo Milk",
    category: "Cheese & Khoya",
    sku: "MLK-FRESH-PANEER-12",
    unit: "kg",
    price: 2500,
    stock: 120,
    featured: true,
    image: img(P.yogurt),
    description: "Fresh Paneer. Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold by the kilogram.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Khoya",
    brand: "Tenvo Milk",
    category: "Cheese & Khoya",
    sku: "MLK-FRESH-KHOYA-13",
    unit: "kg",
    price: 2600,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Fresh Khoya. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Olper's Full Cream Milk 1L",
    brand: "Olper's",
    category: "Packaged Dairy",
    sku: "MLK-OLPER-S-FULL-CREAM-MILK-1L-14",
    unit: "litre",
    price: 380,
    stock: 120,
    featured: true,
    image: img(P.milk),
    description: "Olper's Full Cream Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Nurpur Full Cream Milk 1L",
    brand: "Nurpur",
    category: "Packaged Dairy",
    sku: "MLK-NURPUR-FULL-CREAM-MILK-1L-15",
    unit: "litre",
    price: 380,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Nurpur Full Cream Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Dayfresh Milk 1L",
    brand: "Dayfresh",
    category: "Packaged Dairy",
    sku: "MLK-DAYFRESH-MILK-1L-16",
    unit: "litre",
    price: 360,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Dayfresh Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Nestlé Everyday Milk Powder 400g",
    brand: "Nestlé",
    category: "Packaged Dairy",
    sku: "MLK-NESTL-EVERYDAY-MILK-POWDER-400G-17",
    unit: "pack",
    price: 1150,
    stock: 60,
    featured: false,
    image: img(P.milk),
    description: "Nestlé Everyday Milk Powder 400g. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per pack.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Olper's Cream 200ml",
    brand: "Olper's",
    category: "Cream & Butter",
    sku: "MLK-OLPER-S-CREAM-200ML-18",
    unit: "pack",
    price: 240,
    stock: 60,
    featured: false,
    image: img(P.milk),
    description: "Olper's Cream 200ml. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per pack.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Farm Fresh Eggs (Dozen)",
    brand: "Tenvo Milk",
    category: "Eggs",
    sku: "MLK-FARM-FRESH-EGGS-DOZEN-19",
    unit: "dozen",
    price: 420,
    stock: 60,
    featured: true,
    image: img(P.produce),
    description: "Farm Fresh Eggs (Dozen). Fresh dairy from Tenvo Milk Demo (sourced from purequalitymilk.com). Sold per dozen.",
    domain_data: {"source":"purequalitymilk.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Barfi 500g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-BARFI-500G-20",
    unit: "pack",
    price: 800,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Barfi 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Gulab Jamun 500g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-GULAB-JAMUN-500G-21",
    unit: "pack",
    price: 700,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Gulab Jamun 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Special Malai Lassi Glass",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-SPECIAL-MALAI-LASSI-GLASS-22",
    unit: "pcs",
    price: 220,
    stock: 60,
    featured: true,
    image: img(P.drink2),
    description: "Special Malai Lassi Glass. Fresh dairy from Tenvo Milk Demo (sourced from foodpanda-milk-shops). Sold per pcs.",
    domain_data: {"source":"foodpanda-milk-shops","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Prema Full Cream Milk 1L",
    brand: "Prema",
    category: "Packaged Dairy",
    sku: "MLK-PREMA-FULL-CREAM-MILK-1L-23",
    unit: "litre",
    price: 370,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Prema Full Cream Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Haleeb Full Cream Milk 1L",
    brand: "Haleeb",
    category: "Packaged Dairy",
    sku: "MLK-HALEEB-FULL-CREAM-MILK-1L-24",
    unit: "litre",
    price: 365,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Haleeb Full Cream Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Milkland UHT Milk 1L",
    brand: "Milkland",
    category: "Packaged Dairy",
    sku: "MLK-MILKLAND-UHT-MILK-1L-25",
    unit: "litre",
    price: 350,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Milkland UHT Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per litre.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Anhaar Farm Fresh Milk",
    brand: "Anhaar",
    category: "Fresh Milk",
    sku: "MLK-ANHAAR-FARM-FRESH-MILK-26",
    unit: "kg",
    price: 230,
    stock: 120,
    featured: true,
    image: img(P.milk),
    description: "Anhaar Farm Fresh Milk. Fresh dairy from Tenvo Milk Demo (sourced from anhaar.pk). Sold by the kilogram.",
    domain_data: {"source":"anhaar.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Rabri 500g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-RABRI-500G-27",
    unit: "pack",
    price: 550,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Rabri 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Sweet Lassi Glass",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-SWEET-LASSI-GLASS-28",
    unit: "pcs",
    price: 189,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Sweet Lassi Glass. Fresh dairy from Tenvo Milk Demo (sourced from foodpanda-milk-shops). Sold per pcs.",
    domain_data: {"source":"foodpanda-milk-shops","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Nurpur Cream 200ml",
    brand: "Nurpur",
    category: "Cream & Butter",
    sku: "MLK-NURPUR-CREAM-200ML-29",
    unit: "pack",
    price: 230,
    stock: 60,
    featured: false,
    image: img(P.milk),
    description: "Nurpur Cream 200ml. Fresh dairy from Tenvo Milk Demo (sourced from brand-retail). Sold per pack.",
    domain_data: {"source":"brand-retail","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Desi Ghee 500g",
    brand: "Tenvo Milk",
    category: "Ghee",
    sku: "MLK-DESI-GHEE-500G-30",
    unit: "pack",
    price: 2100,
    stock: 60,
    featured: true,
    image: img(P.aisle),
    description: "Desi Ghee 500g. Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold per pack.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Homemade Dahi 500g",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-HOMEMADE-DAHI-500G-31",
    unit: "pack",
    price: 140,
    stock: 60,
    featured: true,
    image: img(P.yogurt),
    description: "Homemade Dahi 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Paneer 500g",
    brand: "Tenvo Milk",
    category: "Cheese & Khoya",
    sku: "MLK-FRESH-PANEER-500G-32",
    unit: "pack",
    price: 1300,
    stock: 60,
    featured: true,
    image: img(P.yogurt),
    description: "Fresh Paneer 500g. Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold per pack.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Pheeki Lassi Glass 1pc",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-PHEEKI-LASSI-GLASS-1PC-33",
    unit: "pcs",
    price: 169,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Pheeki Lassi Glass 1pc. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Doodh Soda 500ml",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-DOODH-SODA-500ML-34",
    unit: "pcs",
    price: 299,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Doodh Soda 500ml. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Yogurt 1kg",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-YOGURT-1KG-35",
    unit: "kg",
    price: 408,
    stock: 120,
    featured: false,
    image: img(P.yogurt),
    description: "Yogurt 1kg. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold by the kilogram.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Yogurt 500g",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-FRESH-YOGURT-500G-36",
    unit: "pack",
    price: 204,
    stock: 60,
    featured: false,
    image: img(P.yogurt),
    description: "Fresh Yogurt 500g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Pakola Doodh Soda Glass 1pc",
    brand: "Pakola",
    category: "Lassi & Drinks",
    sku: "MLK-PAKOLA-DOODH-SODA-GLASS-1PC-37",
    unit: "pcs",
    price: 119,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Pakola Doodh Soda Glass 1pc. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Milk 1L",
    brand: "Tenvo Milk",
    category: "Fresh Milk",
    sku: "MLK-FRESH-MILK-1L-38",
    unit: "litre",
    price: 278,
    stock: 120,
    featured: false,
    image: img(P.milk),
    description: "Fresh Milk 1L. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per litre.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Chocolate Lassi Glass 1pc",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-CHOCOLATE-LASSI-GLASS-1PC-39",
    unit: "pcs",
    price: 249,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Chocolate Lassi Glass 1pc. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Fresh Yogurt 250g",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-FRESH-YOGURT-250G-40",
    unit: "pack",
    price: 102,
    stock: 60,
    featured: false,
    image: img(P.yogurt),
    description: "Fresh Yogurt 250g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Mango Lassi Glass 1pc",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-MANGO-LASSI-GLASS-1PC-41",
    unit: "pcs",
    price: 289,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Mango Lassi Glass 1pc. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Rose Milk Glass 1pc",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-ROSE-MILK-GLASS-1PC-42",
    unit: "pcs",
    price: 149,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Rose Milk Glass 1pc. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pcs.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Dawn White Bread Vitamin Enriched Medium 1 Packet",
    brand: "Dawn",
    category: "Bakery Staples",
    sku: "MLK-DAWN-WHITE-BREAD-VITAMIN-ENRICHED-ME-43",
    unit: "pack",
    price: 189,
    stock: 60,
    featured: false,
    image: img(P.bread),
    description: "Dawn White Bread Vitamin Enriched Medium 1 Packet. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Nurpur Butter 100g",
    brand: "Nurpur",
    category: "Cream & Butter",
    sku: "MLK-NURPUR-BUTTER-100G-44",
    unit: "pack",
    price: 574,
    stock: 60,
    featured: false,
    image: img(P.milk),
    description: "Nurpur Butter 100g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Brady's Bread Plain Large 850g",
    brand: "Brady's",
    category: "Bakery Staples",
    sku: "MLK-BRADY-S-BREAD-PLAIN-LARGE-850G-45",
    unit: "pack",
    price: 266,
    stock: 60,
    featured: false,
    image: img(P.bread),
    description: "Brady's Bread Plain Large 850g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Bake Parlor Bread Small 440g",
    brand: "Bake Parlor",
    category: "Bakery Staples",
    sku: "MLK-BAKE-PARLOR-BREAD-SMALL-440G-46",
    unit: "pack",
    price: 139,
    stock: 60,
    featured: false,
    image: img(P.bread),
    description: "Bake Parlor Bread Small 440g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Doodh Jalebi 250g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-DOODH-JALEBI-250G-48",
    unit: "pack",
    price: 169,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Doodh Jalebi 250g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Kheer | 250 g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-KHEER-250-G-49",
    unit: "kg",
    price: 219,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Kheer | 250 g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold by the kilogram.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Brady's Bread Milky Medium 650g",
    brand: "Brady's",
    category: "Bakery Staples",
    sku: "MLK-BRADY-S-BREAD-MILKY-MEDIUM-650G-50",
    unit: "pack",
    price: 189,
    stock: 60,
    featured: false,
    image: img(P.bread),
    description: "Brady's Bread Milky Medium 650g. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Dawn Milky Bread Small - 1 Packet",
    brand: "Dawn",
    category: "Bakery Staples",
    sku: "MLK-DAWN-MILKY-BREAD-SMALL-1-PACKET-51",
    unit: "pack",
    price: 139,
    stock: 60,
    featured: false,
    image: img(P.bread),
    description: "Dawn Milky Bread Small - 1 Packet. Fresh dairy from Tenvo Milk Demo (sourced from bismillah-foodpanda-archive). Sold per pack.",
    domain_data: {"source":"bismillah-foodpanda-archive","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Yogurt / Dahi",
    brand: "Tenvo Milk",
    category: "Yogurt / Dahi",
    sku: "MLK-YOGURT-DAHI-52",
    unit: "kg",
    price: 260,
    stock: 120,
    featured: false,
    image: img(P.yogurt),
    description: "Yogurt / Dahi. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Lassi 500g",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-LASSI-500G-53",
    unit: "pcs",
    price: 220,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Lassi 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pcs.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Kheer 1kg",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-KHEER-1KG-54",
    unit: "kg",
    price: 800,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Kheer 1kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Kheer 500g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-KHEER-500G-55",
    unit: "pack",
    price: 400,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Kheer 500g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Kheer 220g",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-KHEER-220G-56",
    unit: "pack",
    price: 200,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Kheer 220g. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pack.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Badami Doodh 450ml",
    brand: "Tenvo Milk",
    category: "Lassi & Drinks",
    sku: "MLK-BADAMI-DOODH-450ML-57",
    unit: "pcs",
    price: 180,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Badami Doodh 450ml. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pcs.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Barfi 1kg",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-BARFI-1KG-58",
    unit: "kg",
    price: 1600,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Barfi 1kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Dhoda 1kg",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-DHODA-1KG-59",
    unit: "kg",
    price: 1600,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Dhoda 1kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Gulab Jamun 1kg",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-GULAB-JAMUN-1KG-60",
    unit: "kg",
    price: 1400,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Gulab Jamun 1kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Garm Gulab Jamun",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-GARM-GULAB-JAMUN-61",
    unit: "pcs",
    price: 120,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Garm Gulab Jamun. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pcs.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Qalaqand 1kg",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-QALAQAND-1KG-62",
    unit: "kg",
    price: 1600,
    stock: 120,
    featured: false,
    image: img(P.aisle),
    description: "Qalaqand 1kg. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold by the kilogram.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Khoya Kulfi",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-KHOYA-KULFI-63",
    unit: "pcs",
    price: 100,
    stock: 60,
    featured: false,
    image: img(P.aisle),
    description: "Khoya Kulfi. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pcs.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Badami Kulfi",
    brand: "Tenvo Milk",
    category: "Dairy Sweets",
    sku: "MLK-BADAMI-KULFI-64",
    unit: "pcs",
    price: 120,
    stock: 60,
    featured: false,
    image: img(P.drink2),
    description: "Badami Kulfi. Fresh dairy from Tenvo Milk Demo (sourced from punjabmilkshop.com-menu). Sold per pcs.",
    domain_data: {"source":"punjabmilkshop.com-menu","chill":true,"fatpercent":""},
  }),
  milkProduct({
    name: "Paneer (Fresh Cottage Cheese)",
    brand: "Tenvo Milk",
    category: "Cheese & Khoya",
    sku: "MLK-PANEER-FRESH-COTTAGE-CHEESE-65",
    unit: "kg",
    price: 2500,
    stock: 120,
    featured: false,
    image: img(P.yogurt),
    description: "Paneer (Fresh Cottage Cheese). Fresh dairy from Tenvo Milk Demo (sourced from purenest.pk). Sold by the kilogram.",
    domain_data: {"source":"purenest.pk","chill":true,"fatpercent":""},
  }),
];

export const MILK_SHOP_SEED_PRODUCT_COUNT = MILK_SHOP_SEED_PRODUCTS.length;
