/**
 * Tenvo Marbles demo catalog — porcelain/ceramic collections + natural stone.
 * Taxonomy inspired by STILE spaces/collections and SK Stones / SMB Marble materials.
 * Images: Unsplash via tilesDemoImages (not competitor CDNs).
 */
import { getTilesDemoImage } from './tilesDemoImages.js';

/** @type {string[]} */
export const TILES_SEED_CATEGORIES = [
  'Floor Tiles',
  'Wall Tiles',
  'Outdoor Tiles',
  'Bathroom Tiles',
  'Kitchen Tiles',
  'Marble',
  'Granite',
  'Onyx',
  'Travertine',
  'Limestone',
  'Mosaic Tiles',
  'Adhesives',
];

/**
 * @param {object} partial
 * @returns {Record<string, unknown>}
 */
function tileProduct(partial) {
  const {
    name,
    category,
    sku,
    price,
    compare_price,
    unit = 'box',
    stock = 80,
    featured = false,
    imageKey = 'porcelain',
    description,
    domain_data = {},
  } = partial;
  const cost = Math.round(Number(price) * 0.72);
  return {
    name,
    brand: 'Tenvo Marbles',
    category,
    unit,
    price,
    compare_price: compare_price ?? Math.round(Number(price) * 1.18),
    cost_price: cost,
    stock,
    sku,
    description:
      description ||
      `${name}. Premium surface for residential and commercial projects with shade-matched lots.`,
    image_url: getTilesDemoImage(imageKey, 1200),
    imageCredit: 'Unsplash',
    is_featured: featured,
    domain_data: {
      designpattern: domain_data.designpattern || name,
      toneshadeid: domain_data.toneshadeid || 'A-01',
      sizemm: domain_data.sizemm || '600x600',
      finish: domain_data.finish || 'Polished',
      materialtype: domain_data.materialtype || 'Porcelain',
      collection: domain_data.collection || 'Elite',
      spaceuse: domain_data.spaceuse || 'Living Room',
      thicknessmm: domain_data.thicknessmm ?? 9,
      origin: domain_data.origin || 'Local',
      ...domain_data,
    },
  };
}

/** @type {Array<Record<string, unknown>>} */
export const TILES_SEED_PRODUCTS = [
  tileProduct({
    name: 'Elite Carrara Vein 60x60',
    category: 'Floor Tiles',
    sku: 'TM-ELITE-001',
    price: 6800,
    featured: true,
    imageKey: 'marbleWhite',
    domain_data: {
      designpattern: 'Carrara vein',
      toneshadeid: 'E-12',
      sizemm: '600x600',
      finish: 'Polished',
      materialtype: 'Porcelain',
      collection: 'Elite',
      spaceuse: 'Living Room',
    },
  }),
  tileProduct({
    name: 'Elite Sahara Beige 60x60',
    category: 'Floor Tiles',
    sku: 'TM-ELITE-002',
    price: 6200,
    featured: true,
    imageKey: 'collectionElite',
    domain_data: {
      designpattern: 'Sandy beige',
      toneshadeid: 'E-08',
      finish: 'Lappato',
      collection: 'Elite',
      spaceuse: 'Dining Room',
    },
  }),
  tileProduct({
    name: 'Elite Grey Ripple 80x80',
    category: 'Floor Tiles',
    sku: 'TM-ELITE-003',
    price: 8900,
    imageKey: 'porcelain',
    domain_data: {
      designpattern: 'Smooth ripple',
      toneshadeid: 'E-22',
      sizemm: '800x800',
      finish: 'Matte',
      collection: 'Elite',
    },
  }),
  tileProduct({
    name: 'Modish Ivory Marble Look 60x120',
    category: 'Floor Tiles',
    sku: 'TM-MOD-001',
    price: 9800,
    featured: true,
    imageKey: 'living',
    domain_data: {
      designpattern: 'Ivory marble',
      toneshadeid: 'M-01',
      sizemm: '600x1200',
      finish: 'Polished',
      collection: 'Modish',
      spaceuse: 'Living Room',
    },
  }),
  tileProduct({
    name: 'Modish Soft Grey 60x60',
    category: 'Floor Tiles',
    sku: 'TM-MOD-002',
    price: 5400,
    imageKey: 'heroFloor',
    domain_data: {
      designpattern: 'Soft grey',
      toneshadeid: 'M-06',
      finish: 'Matte',
      collection: 'Modish',
    },
  }),
  tileProduct({
    name: 'Wooden Plank Oak Brown 20x120',
    category: 'Floor Tiles',
    sku: 'TM-WOOD-001',
    price: 7200,
    featured: true,
    imageKey: 'woodPlank',
    domain_data: {
      designpattern: 'Oak grain',
      toneshadeid: 'W-04',
      sizemm: '200x1200',
      finish: 'Matte',
      materialtype: 'Porcelain',
      collection: 'Wooden Planks',
      spaceuse: 'Bedroom',
    },
  }),
  tileProduct({
    name: 'Wooden Plank Ash Grey 20x120',
    category: 'Floor Tiles',
    sku: 'TM-WOOD-002',
    price: 7400,
    imageKey: 'bedroom',
    domain_data: {
      designpattern: 'Ash grey wood',
      toneshadeid: 'W-09',
      sizemm: '200x1200',
      finish: 'Matte',
      collection: 'Wooden Planks',
      spaceuse: 'Bedroom',
    },
  }),
  tileProduct({
    name: 'Signature Lapato Pearl 60x60',
    category: 'Floor Tiles',
    sku: 'TM-SIG-001',
    price: 11200,
    featured: true,
    imageKey: 'collectionSignature',
    domain_data: {
      designpattern: 'Pearl vein',
      toneshadeid: 'S-01',
      finish: 'Lappato',
      collection: 'Signature',
      materialtype: 'Porcelain',
    },
  }),
  tileProduct({
    name: 'Signature Anti-Slip Graphite 60x60',
    category: 'Outdoor Tiles',
    sku: 'TM-SIG-002',
    price: 8600,
    imageKey: 'outdoor',
    domain_data: {
      designpattern: 'Graphite stone',
      toneshadeid: 'S-14',
      finish: 'Anti-Slip',
      collection: 'Signature',
      spaceuse: 'Outdoor',
      materialtype: 'Vitrified',
    },
  }),
  tileProduct({
    name: 'Tile Art Geometric Ivory 30x30',
    category: 'Wall Tiles',
    sku: 'TM-ART-001',
    price: 4800,
    featured: true,
    imageKey: 'mosaic',
    domain_data: {
      designpattern: 'Geometric repeat',
      toneshadeid: 'A-03',
      sizemm: '300x300',
      finish: 'Matte',
      collection: 'Tile Art',
      spaceuse: 'Bathroom',
      materialtype: 'Ceramic',
    },
  }),
  tileProduct({
    name: 'Tile Art Ornamental Border 10x30',
    category: 'Wall Tiles',
    sku: 'TM-ART-002',
    price: 3200,
    imageKey: 'heroWall',
    domain_data: {
      designpattern: 'Ornamental border',
      toneshadeid: 'A-07',
      sizemm: '100x300',
      finish: 'Gloss',
      collection: 'Tile Art',
      materialtype: 'Ceramic',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Vitrified Patio Stone 40x40',
    category: 'Outdoor Tiles',
    sku: 'TM-VIT-001',
    price: 5900,
    featured: true,
    imageKey: 'vitrified',
    domain_data: {
      designpattern: 'Natural patio',
      toneshadeid: 'V-02',
      sizemm: '400x400',
      finish: 'Rustic',
      collection: 'Vitrified',
      materialtype: 'Vitrified',
      spaceuse: 'Outdoor',
      thicknessmm: 12,
    },
  }),
  tileProduct({
    name: 'Glossy Wall White 30x60',
    category: 'Wall Tiles',
    sku: 'TM-WALL-001',
    price: 3600,
    imageKey: 'heroWall',
    domain_data: {
      designpattern: 'Plain white',
      toneshadeid: 'WL-01',
      sizemm: '300x600',
      finish: 'Polished',
      materialtype: 'Ceramic',
      collection: 'Modish',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Matte Wall Soft Beige 30x60',
    category: 'Wall Tiles',
    sku: 'TM-WALL-002',
    price: 3800,
    featured: true,
    imageKey: 'bathroom',
    domain_data: {
      designpattern: 'Soft beige',
      toneshadeid: 'WL-05',
      sizemm: '300x600',
      finish: 'Matte',
      materialtype: 'Ceramic',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Kitchen Subway Gloss 10x30',
    category: 'Kitchen Tiles',
    sku: 'TM-KIT-001',
    price: 2900,
    featured: true,
    imageKey: 'kitchen',
    domain_data: {
      designpattern: 'Subway',
      toneshadeid: 'K-01',
      sizemm: '100x300',
      finish: 'Polished',
      materialtype: 'Ceramic',
      spaceuse: 'Kitchen',
    },
  }),
  tileProduct({
    name: 'Kitchen Hexagon Grey Mosaic',
    category: 'Kitchen Tiles',
    sku: 'TM-KIT-002',
    price: 5100,
    imageKey: 'mosaic',
    unit: 'box',
    domain_data: {
      designpattern: 'Hexagon mosaic',
      toneshadeid: 'K-11',
      sizemm: 'sheet 300x300',
      finish: 'Matte',
      materialtype: 'Mosaic',
      spaceuse: 'Kitchen',
    },
  }),
  tileProduct({
    name: 'Bathroom Pearl Relief 30x60',
    category: 'Bathroom Tiles',
    sku: 'TM-BATH-001',
    price: 4200,
    featured: true,
    imageKey: 'bathroom',
    domain_data: {
      designpattern: 'Pearl relief',
      toneshadeid: 'B-03',
      sizemm: '300x600',
      finish: 'Matte',
      materialtype: 'Ceramic',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Bathroom Dark Charcoal Floor 60x60',
    category: 'Bathroom Tiles',
    sku: 'TM-BATH-002',
    price: 6100,
    imageKey: 'heroFloor',
    domain_data: {
      designpattern: 'Charcoal stone',
      toneshadeid: 'B-18',
      sizemm: '600x600',
      finish: 'Anti-Slip',
      materialtype: 'Porcelain',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Carrara White Marble Slab',
    category: 'Marble',
    sku: 'TM-MAR-001',
    price: 520,
    unit: 'sqft',
    stock: 1200,
    featured: true,
    imageKey: 'marbleWhite',
    domain_data: {
      designpattern: 'Carrara white',
      toneshadeid: 'MR-CW',
      sizemm: 'slab',
      finish: 'Polished',
      materialtype: 'Marble',
      collection: 'Imported Marble',
      spaceuse: 'Kitchen',
      thicknessmm: 20,
      origin: 'Imported',
    },
  }),
  tileProduct({
    name: 'Indus Gold Marble',
    category: 'Marble',
    sku: 'TM-MAR-002',
    price: 380,
    unit: 'sqft',
    stock: 900,
    featured: true,
    imageKey: 'marbleGold',
    domain_data: {
      designpattern: 'Gold vein',
      toneshadeid: 'MR-IG',
      sizemm: 'slab',
      finish: 'Polished',
      materialtype: 'Marble',
      origin: 'Pakistan',
      spaceuse: 'Living Room',
      thicknessmm: 18,
    },
  }),
  tileProduct({
    name: 'Black and Gold Marble',
    category: 'Marble',
    sku: 'TM-MAR-003',
    price: 450,
    unit: 'sqft',
    stock: 700,
    featured: true,
    imageKey: 'collectionElite',
    domain_data: {
      designpattern: 'Black gold vein',
      toneshadeid: 'MR-BG',
      finish: 'Polished',
      materialtype: 'Marble',
      origin: 'Pakistan',
      thicknessmm: 20,
    },
  }),
  tileProduct({
    name: 'Sahara Beige Marble',
    category: 'Marble',
    sku: 'TM-MAR-004',
    price: 320,
    unit: 'sqft',
    stock: 850,
    imageKey: 'travertine',
    domain_data: {
      designpattern: 'Sahara beige',
      toneshadeid: 'MR-SB',
      finish: 'Honed',
      materialtype: 'Marble',
      origin: 'Pakistan',
    },
  }),
  tileProduct({
    name: 'Black Galaxy Granite',
    category: 'Granite',
    sku: 'TM-GRAN-001',
    price: 410,
    unit: 'sqft',
    stock: 650,
    featured: true,
    imageKey: 'granite',
    domain_data: {
      designpattern: 'Galaxy speckles',
      toneshadeid: 'GR-BG',
      finish: 'Polished',
      materialtype: 'Granite',
      spaceuse: 'Kitchen',
      origin: 'Imported',
      thicknessmm: 20,
    },
  }),
  tileProduct({
    name: 'Steel Grey Granite',
    category: 'Granite',
    sku: 'TM-GRAN-002',
    price: 290,
    unit: 'sqft',
    stock: 780,
    imageKey: 'granite',
    domain_data: {
      designpattern: 'Steel grey',
      toneshadeid: 'GR-SG',
      finish: 'Flamed',
      materialtype: 'Granite',
      spaceuse: 'Outdoor',
      origin: 'Local',
    },
  }),
  tileProduct({
    name: 'White Onyx Slab',
    category: 'Onyx',
    sku: 'TM-ONYX-001',
    price: 780,
    unit: 'sqft',
    stock: 320,
    featured: true,
    imageKey: 'onyx',
    domain_data: {
      designpattern: 'Translucent white',
      toneshadeid: 'OX-WH',
      finish: 'Polished',
      materialtype: 'Onyx',
      spaceuse: 'Commercial',
      origin: 'Pakistan',
      thicknessmm: 20,
    },
  }),
  tileProduct({
    name: 'Dark Green Onyx',
    category: 'Onyx',
    sku: 'TM-ONYX-002',
    price: 720,
    unit: 'sqft',
    stock: 280,
    featured: true,
    imageKey: 'onyx',
    domain_data: {
      designpattern: 'Dark green bands',
      toneshadeid: 'OX-DG',
      finish: 'Polished',
      materialtype: 'Onyx',
      origin: 'Pakistan',
    },
  }),
  tileProduct({
    name: 'Multi Green Onyx',
    category: 'Onyx',
    sku: 'TM-ONYX-003',
    price: 690,
    unit: 'sqft',
    stock: 260,
    imageKey: 'onyx',
    domain_data: {
      designpattern: 'Multi green',
      toneshadeid: 'OX-MG',
      finish: 'Polished',
      materialtype: 'Onyx',
      origin: 'Pakistan',
    },
  }),
  tileProduct({
    name: 'Silver Travertine',
    category: 'Travertine',
    sku: 'TM-TRAV-001',
    price: 340,
    unit: 'sqft',
    stock: 540,
    featured: true,
    imageKey: 'travertine',
    domain_data: {
      designpattern: 'Silver porous',
      toneshadeid: 'TR-SV',
      finish: 'Honed',
      materialtype: 'Travertine',
      spaceuse: 'Outdoor',
      origin: 'Imported',
    },
  }),
  tileProduct({
    name: 'Red Travertine',
    category: 'Travertine',
    sku: 'TM-TRAV-002',
    price: 360,
    unit: 'sqft',
    stock: 410,
    imageKey: 'marbleGold',
    domain_data: {
      designpattern: 'Warm red',
      toneshadeid: 'TR-RD',
      finish: 'Filled Polished',
      materialtype: 'Travertine',
      origin: 'Imported',
    },
  }),
  tileProduct({
    name: 'White Limestone',
    category: 'Limestone',
    sku: 'TM-LIME-001',
    price: 260,
    unit: 'sqft',
    stock: 600,
    featured: true,
    imageKey: 'limestone',
    domain_data: {
      designpattern: 'Soft white grain',
      toneshadeid: 'LM-WH',
      finish: 'Honed',
      materialtype: 'Limestone',
      spaceuse: 'Facade',
      origin: 'Pakistan',
    },
  }),
  tileProduct({
    name: 'Bubble Limestone',
    category: 'Limestone',
    sku: 'TM-LIME-002',
    price: 280,
    unit: 'sqft',
    stock: 480,
    imageKey: 'limestone',
    domain_data: {
      designpattern: 'Bubble texture',
      toneshadeid: 'LM-BB',
      finish: 'Sandblasted',
      materialtype: 'Limestone',
      spaceuse: 'Outdoor',
    },
  }),
  tileProduct({
    name: 'Glass Mosaic Mix Sheet',
    category: 'Mosaic Tiles',
    sku: 'TM-MOS-001',
    price: 4500,
    featured: true,
    imageKey: 'mosaic',
    domain_data: {
      designpattern: 'Mixed glass',
      toneshadeid: 'MS-01',
      sizemm: 'sheet 300x300',
      finish: 'Gloss',
      materialtype: 'Mosaic',
      spaceuse: 'Bathroom',
    },
  }),
  tileProduct({
    name: 'Stone Mosaic Hex Pack',
    category: 'Mosaic Tiles',
    sku: 'TM-MOS-002',
    price: 5200,
    imageKey: 'mosaic',
    domain_data: {
      designpattern: 'Stone hex',
      toneshadeid: 'MS-08',
      finish: 'Matte',
      materialtype: 'Mosaic',
      spaceuse: 'Kitchen',
    },
  }),
  tileProduct({
    name: 'Premium Tile Adhesive 20kg',
    category: 'Adhesives',
    sku: 'TM-ADH-001',
    price: 950,
    compare_price: 1100,
    unit: 'bag',
    stock: 400,
    imageKey: 'adhesive',
    domain_data: {
      designpattern: 'Standard set',
      toneshadeid: 'N/A',
      sizemm: '20kg',
      finish: 'N/A',
      materialtype: 'Adhesive',
      collection: 'Building & Installation',
      thicknessmm: 0,
      origin: 'Local',
    },
  }),
  tileProduct({
    name: 'Flexible Stone Adhesive 20kg',
    category: 'Adhesives',
    sku: 'TM-ADH-002',
    price: 1250,
    compare_price: 1450,
    unit: 'bag',
    stock: 280,
    imageKey: 'adhesive',
    domain_data: {
      designpattern: 'Flexible bond',
      toneshadeid: 'N/A',
      sizemm: '20kg',
      finish: 'N/A',
      materialtype: 'Adhesive',
      collection: 'Building & Installation',
      origin: 'Local',
    },
  }),
  tileProduct({
    name: 'Grout Grey 5kg',
    category: 'Adhesives',
    sku: 'TM-ADH-003',
    price: 680,
    compare_price: 780,
    unit: 'bag',
    stock: 350,
    imageKey: 'adhesive',
    domain_data: {
      designpattern: 'Grey grout',
      toneshadeid: 'GR-GY',
      sizemm: '5kg',
      finish: 'N/A',
      materialtype: 'Adhesive',
      collection: 'Building & Installation',
    },
  }),
];
