/**
 * Tenvo Tyre Store demo / registration catalog.
 * Local lines from GTR archive; imported models from Techno Tyres archive naming.
 * Images: archive CDN assets in tyreArchiveAssets.js.
 */
import {
  TYRE_GTR_PRODUCT_IMAGES as G,
  TYRE_TECHNO_PRODUCT_IMAGES as T,
  TYRE_HERO_IMAGES,
  TYRE_BAY_SERVICE_IMAGES,
} from './tyreArchiveAssets.js';

/** @type {string[]} */
export const TYRE_SEED_CATEGORIES = [
  'Passenger Car',
  'SUV / Crossover',
  'Light Truck',
  'Commercial / OTR',
  'Motorcycle / Rickshaw',
  'Tractor / Agri',
  'Alloy Rims',
  'Services (Fitting)',
];

/**
 * @param {object} partial
 * @returns {Record<string, unknown>}
 */
function tyreProduct(partial) {
  const {
    name,
    brand,
    category,
    sku,
    price,
    compare_price,
    unit = 'pcs',
    stock = 20,
    featured = false,
    image,
    description,
    domain_data = {},
  } = partial;
  const size = String(domain_data.tyresize || '');
  const rimMatch = size.match(/R(\d{2})/i);
  const rim = domain_data.rimsize || (rimMatch ? rimMatch[1] : '');
  const cost = Math.round(Number(price) * 0.78);
  return {
    name,
    brand,
    category,
    unit,
    price,
    compare_price: compare_price ?? Math.round(Number(price) * 1.12),
    cost_price: cost,
    stock,
    sku,
    description:
      description ||
      `${name}. ${brand} ${category.toLowerCase()} tyre with size ${size || 'as marked'}.`,
    image_url: image,
    imageCredit: 'Archive seed',
    is_featured: featured,
    domain_data: {
      tyresize: size,
      loadindex: domain_data.loadindex || '',
      speedrating: domain_data.speedrating || 'H',
      rimsize: String(rim || ''),
      runflat: domain_data.runflat || 'No',
      sourcing: domain_data.sourcing || 'imported',
      brand: brand,
      ...domain_data,
    },
  };
}

/** Marketing hero for gallery / demo meta */
export const TYRE_MARKETING_HERO_IMAGE = TYRE_HERO_IMAGES.banner1;

/** @type {Array<Record<string, unknown>>} */
export const TYRE_SEED_PRODUCTS = [
  // ── Local GTR passenger ───────────────────────────────────────────
  tyreProduct({
    name: 'GTR BG Econo 185/65 R15',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-ECONO-1856515',
    price: 14200,
    featured: true,
    stock: 36,
    image: G.econo,
    description: 'Local economy touring tyre for compact sedans and hatchbacks. Balanced wear and wet grip for city driving.',
    domain_data: { tyresize: '185/65R15', loadindex: '88', speedrating: 'H', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR BG Falcon 195/65 R15',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-FALCON-1956515',
    price: 16800,
    featured: true,
    stock: 28,
    image: G.falcon,
    domain_data: { tyresize: '195/65R15', loadindex: '91', speedrating: 'H', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR BG Luxo Plus 205/55 R16',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-LUXO-2055516',
    price: 21500,
    featured: true,
    stock: 22,
    image: G.luxoPlus,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR BG Max Sport 215/55 R17',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-MAXSP-2155517',
    price: 26800,
    stock: 16,
    image: G.maxSport,
    domain_data: { tyresize: '215/55R17', loadindex: '94', speedrating: 'W', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Aqua Grip 205/60 R16',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-AQUA-2056016',
    price: 19800,
    stock: 20,
    image: G.aquaGrip,
    description: 'Wet-weather focused passenger radial for monsoon conditions.',
    domain_data: { tyresize: '205/60R16', loadindex: '92', speedrating: 'H', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Euro Glide 175/70 R13',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-EGLIDE-1757013',
    price: 9800,
    stock: 40,
    image: G.euroGlide,
    domain_data: { tyresize: '175/70R13', loadindex: '82', speedrating: 'T', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Euro Kruze 185/70 R14',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-EKRUZE-1857014',
    price: 11800,
    stock: 32,
    image: G.euroKruze,
    domain_data: { tyresize: '185/70R14', loadindex: '88', speedrating: 'H', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Euro Tycoon 195/55 R16',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-ETYC-1955516',
    price: 18900,
    stock: 18,
    image: G.euroTycoon,
    domain_data: { tyresize: '195/55R16', loadindex: '87', speedrating: 'V', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Challenger 205/65 R15',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-CHAL-2056515',
    price: 17200,
    stock: 24,
    image: G.challenger,
    domain_data: { tyresize: '205/65R15', loadindex: '94', speedrating: 'H', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Black Cobra 225/45 R17',
    brand: 'GTR',
    category: 'Passenger Car',
    sku: 'TT-GTR-COBRA-2254517',
    price: 29500,
    stock: 12,
    image: G.blackCobra,
    domain_data: { tyresize: '225/45R17', loadindex: '94', speedrating: 'W', sourcing: 'local' },
  }),

  // ── Local SUV ─────────────────────────────────────────────────────
  tyreProduct({
    name: 'GTR BG Raptor 265/65 R17',
    brand: 'GTR',
    category: 'SUV / Crossover',
    sku: 'TT-GTR-RAPT-2656517',
    price: 34500,
    featured: true,
    stock: 14,
    image: G.raptor,
    description: 'Local SUV all-terrain pattern for pickups and crossovers.',
    domain_data: { tyresize: '265/65R17', loadindex: '112', speedrating: 'T', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR BG Velotrak Plus 235/60 R18',
    brand: 'GTR',
    category: 'SUV / Crossover',
    sku: 'TT-GTR-VELO-2356018',
    price: 38500,
    featured: true,
    stock: 10,
    image: G.velotrakPlus,
    domain_data: { tyresize: '235/60R18', loadindex: '103', speedrating: 'V', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Power Terrain 255/70 R16',
    brand: 'GTR',
    category: 'SUV / Crossover',
    sku: 'TT-GTR-PTER-2557016',
    price: 31200,
    stock: 12,
    image: G.powerTerrain,
    domain_data: { tyresize: '255/70R16', loadindex: '111', speedrating: 'T', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Thunder Max 265/60 R18',
    brand: 'GTR',
    category: 'SUV / Crossover',
    sku: 'TT-GTR-THUN-2656018',
    price: 39800,
    stock: 8,
    image: G.thunderMax,
    domain_data: { tyresize: '265/60R18', loadindex: '110', speedrating: 'H', sourcing: 'local' },
  }),

  // ── Light truck / commercial local ────────────────────────────────
  tyreProduct({
    name: 'GTR BG Alro Plus 195R15C',
    brand: 'GTR',
    category: 'Light Truck',
    sku: 'TT-GTR-ALRO-195R15C',
    price: 22800,
    stock: 16,
    image: G.alroPlus,
    domain_data: { tyresize: '195R15C', loadindex: '106', speedrating: 'R', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR BG Cargo 205/75 R16C',
    brand: 'GTR',
    category: 'Light Truck',
    sku: 'TT-GTR-CARGO-2057516C',
    price: 26500,
    stock: 14,
    image: G.cargo,
    domain_data: { tyresize: '205/75R16C', loadindex: '110', speedrating: 'R', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Rhino Power 11R22.5',
    brand: 'GTR',
    category: 'Commercial / OTR',
    sku: 'TT-GTR-RHINO-11R225',
    price: 68500,
    stock: 8,
    image: G.rhinoPower,
    domain_data: { tyresize: '11R22.5', loadindex: '148', speedrating: 'M', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Super Excave 17.5-25',
    brand: 'GTR',
    category: 'Commercial / OTR',
    sku: 'TT-GTR-EXCAVE-17525',
    price: 125000,
    stock: 4,
    image: G.superExcave,
    domain_data: { tyresize: '17.5-25', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR HCT 10.00-20',
    brand: 'GTR',
    category: 'Commercial / OTR',
    sku: 'TT-GTR-HCT-100020',
    price: 54000,
    stock: 6,
    image: G.hct,
    domain_data: { tyresize: '10.00-20', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Traction Rib 7.50-16',
    brand: 'GTR',
    category: 'Commercial / OTR',
    sku: 'TT-GTR-TRIB-75016',
    price: 28500,
    stock: 10,
    image: G.tractionRib,
    domain_data: { tyresize: '7.50-16', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR STGR 12.00-24',
    brand: 'GTR',
    category: 'Commercial / OTR',
    sku: 'TT-GTR-STGR-120024',
    price: 98000,
    stock: 4,
    image: G.stgr,
    domain_data: { tyresize: '12.00-24', loadindex: '', speedrating: '', sourcing: 'local' },
  }),

  // ── Motorcycle / agri local ───────────────────────────────────────
  tyreProduct({
    name: 'GTR GQT 90/90-12',
    brand: 'GTR',
    category: 'Motorcycle / Rickshaw',
    sku: 'TT-GTR-GQT-909012',
    price: 4200,
    stock: 48,
    image: G.gqt,
    domain_data: { tyresize: '90/90-12', loadindex: '44', speedrating: 'J', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Agri Gold 12.4-28',
    brand: 'GTR',
    category: 'Tractor / Agri',
    sku: 'TT-GTR-AGOLD-12428',
    price: 52000,
    stock: 6,
    image: G.agriGold,
    domain_data: { tyresize: '12.4-28', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Agri Lug 16.9-28',
    brand: 'GTR',
    category: 'Tractor / Agri',
    sku: 'TT-GTR-ALUG-16928',
    price: 72000,
    stock: 5,
    image: G.agriLug,
    domain_data: { tyresize: '16.9-28', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Agri Power Plus 18.4-30',
    brand: 'GTR',
    category: 'Tractor / Agri',
    sku: 'TT-GTR-APWR-18430',
    price: 89000,
    stock: 4,
    image: G.agriPowerPlus,
    domain_data: { tyresize: '18.4-30', loadindex: '', speedrating: '', sourcing: 'local' },
  }),
  tyreProduct({
    name: 'GTR Agri Trac 11.2-24',
    brand: 'GTR',
    category: 'Tractor / Agri',
    sku: 'TT-GTR-ATRAC-11224',
    price: 41000,
    stock: 6,
    image: G.agriTrac,
    domain_data: { tyresize: '11.2-24', loadindex: '', speedrating: '', sourcing: 'local' },
  }),

  // ── Imported Michelin ─────────────────────────────────────────────
  tyreProduct({
    name: 'Michelin Primacy 4 205/55 R16',
    brand: 'Michelin',
    category: 'Passenger Car',
    sku: 'TT-MIC-P4-2055516',
    price: 48500,
    featured: true,
    stock: 12,
    image: T.p05,
    description: 'Imported premium touring tyre with strong wet braking and longevity.',
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Michelin Primacy 5 215/55 R17',
    brand: 'Michelin',
    category: 'Passenger Car',
    sku: 'TT-MIC-P5-2155517',
    price: 54500,
    stock: 10,
    image: T.p09,
    domain_data: { tyresize: '215/55R17', loadindex: '94', speedrating: 'W', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Michelin Primacy SUV+ 235/60 R18',
    brand: 'Michelin',
    category: 'SUV / Crossover',
    sku: 'TT-MIC-PSUV-2356018',
    price: 62000,
    featured: true,
    stock: 8,
    image: T.p14,
    domain_data: { tyresize: '235/60R18', loadindex: '103', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Michelin Agilis 3 195/75 R16C',
    brand: 'Michelin',
    category: 'Light Truck',
    sku: 'TT-MIC-AG3-1957516C',
    price: 42000,
    stock: 10,
    image: T.p15,
    domain_data: { tyresize: '195/75R16C', loadindex: '107', speedrating: 'R', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Michelin LTX ST 265/65 R17',
    brand: 'Michelin',
    category: 'SUV / Crossover',
    sku: 'TT-MIC-LTX-2656517',
    price: 58000,
    stock: 8,
    image: T.p16,
    domain_data: { tyresize: '265/65R17', loadindex: '112', speedrating: 'T', sourcing: 'imported' },
  }),

  // ── Yokohama / GT Radial / Otani ──────────────────────────────────
  tyreProduct({
    name: 'Yokohama BluEarth E70 205/55 R16',
    brand: 'Yokohama',
    category: 'Passenger Car',
    sku: 'TT-YOK-E70-2055516',
    price: 36500,
    featured: true,
    stock: 14,
    image: T.p21,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Yokohama A460 195/65 R15',
    brand: 'Yokohama',
    category: 'Passenger Car',
    sku: 'TT-YOK-A460-1956515',
    price: 28500,
    stock: 16,
    image: T.p06,
    domain_data: { tyresize: '195/65R15', loadindex: '91', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'GT Radial Champiro BXT Plus 185/65 R15',
    brand: 'GT Radial',
    category: 'Passenger Car',
    sku: 'TT-GTRAD-BXT-1856515',
    price: 16500,
    stock: 24,
    image: T.p10,
    domain_data: { tyresize: '185/65R15', loadindex: '88', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'GT Radial Maxtour All Season 205/55 R16',
    brand: 'GT Radial',
    category: 'Passenger Car',
    sku: 'TT-GTRAD-MAX-2055516',
    price: 19800,
    stock: 18,
    image: T.p07,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'GT Radial Touring VP Plus 195/65 R15',
    brand: 'GT Radial',
    category: 'Passenger Car',
    sku: 'TT-GTRAD-VP-1956515',
    price: 15200,
    stock: 22,
    image: T.p04,
    domain_data: { tyresize: '195/65R15', loadindex: '91', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'GT Radial Savero SUV 235/65 R17',
    brand: 'GT Radial',
    category: 'SUV / Crossover',
    sku: 'TT-GTRAD-SAV-2356517',
    price: 28500,
    stock: 12,
    image: T.p62,
    domain_data: { tyresize: '235/65R17', loadindex: '104', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Otani EK1000 205/55 R16',
    brand: 'Otani',
    category: 'Passenger Car',
    sku: 'TT-OTA-EK1-2055516',
    price: 17800,
    stock: 20,
    image: T.p05,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Otani KC2000 265/65 R17',
    brand: 'Otani',
    category: 'SUV / Crossover',
    sku: 'TT-OTA-KC2-2656517',
    price: 26800,
    stock: 12,
    image: T.p14,
    domain_data: { tyresize: '265/65R17', loadindex: '112', speedrating: 'T', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Winda WP18 185/65 R15',
    brand: 'Winda',
    category: 'Passenger Car',
    sku: 'TT-WIN-WP18-1856515',
    price: 12800,
    stock: 28,
    image: T.p09,
    domain_data: { tyresize: '185/65R15', loadindex: '88', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Hankook Kinergy Eco2 195/65 R15',
    brand: 'Hankook',
    category: 'Passenger Car',
    sku: 'TT-HAN-KE2-1956515',
    price: 24500,
    stock: 16,
    image: T.p15,
    domain_data: { tyresize: '195/65R15', loadindex: '91', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Bridgestone Turanza T005 205/55 R16',
    brand: 'Bridgestone',
    category: 'Passenger Car',
    sku: 'TT-BRI-T005-2055516',
    price: 45500,
    featured: true,
    stock: 10,
    image: T.p16,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Continental ComfortContact CC6 185/65 R15',
    brand: 'Continental',
    category: 'Passenger Car',
    sku: 'TT-CON-CC6-1856515',
    price: 27500,
    stock: 14,
    image: T.p21,
    domain_data: { tyresize: '185/65R15', loadindex: '88', speedrating: 'H', sourcing: 'imported' },
  }),
  tyreProduct({
    name: 'Dunlop SP Sport LM705 205/55 R16',
    brand: 'Dunlop',
    category: 'Passenger Car',
    sku: 'TT-DUN-LM705-2055516',
    price: 32500,
    stock: 12,
    image: T.p06,
    domain_data: { tyresize: '205/55R16', loadindex: '91', speedrating: 'V', sourcing: 'imported' },
  }),

  // ── Alloy rims ────────────────────────────────────────────────────
  tyreProduct({
    name: 'Alloy Rim Set 14 inch (4 pcs)',
    brand: 'Tenvo Wheels',
    category: 'Alloy Rims',
    sku: 'TT-RIM-14-SET4',
    price: 42000,
    unit: 'set',
    stock: 8,
    featured: true,
    image: T.p04,
    description: 'Stylish 14-inch alloy wheel set for compact cars. Sold as a set of four.',
    domain_data: { tyresize: '', rimsize: '14', sourcing: 'imported', loadindex: '', speedrating: '' },
  }),
  tyreProduct({
    name: 'Alloy Rim Set 15 inch (4 pcs)',
    brand: 'Tenvo Wheels',
    category: 'Alloy Rims',
    sku: 'TT-RIM-15-SET4',
    price: 52000,
    unit: 'set',
    stock: 8,
    image: T.p07,
    domain_data: { tyresize: '', rimsize: '15', sourcing: 'imported', loadindex: '', speedrating: '' },
  }),
  tyreProduct({
    name: 'Alloy Rim Set 16 inch (4 pcs)',
    brand: 'Tenvo Wheels',
    category: 'Alloy Rims',
    sku: 'TT-RIM-16-SET4',
    price: 68000,
    unit: 'set',
    stock: 6,
    featured: true,
    image: T.p10,
    domain_data: { tyresize: '', rimsize: '16', sourcing: 'imported', loadindex: '', speedrating: '' },
  }),
  tyreProduct({
    name: 'Alloy Rim Set 17 inch (4 pcs)',
    brand: 'Tenvo Wheels',
    category: 'Alloy Rims',
    sku: 'TT-RIM-17-SET4',
    price: 85000,
    unit: 'set',
    stock: 5,
    image: T.p62,
    domain_data: { tyresize: '', rimsize: '17', sourcing: 'imported', loadindex: '', speedrating: '' },
  }),

  // ── Services ──────────────────────────────────────────────────────
  tyreProduct({
    name: 'Tyre Fitting & Balancing (4 wheels)',
    brand: 'Tenvo Tyre Store',
    category: 'Services (Fitting)',
    sku: 'TT-SVC-FIT-BAL-4',
    price: 2500,
    compare_price: 3000,
    unit: 'set',
    stock: 999,
    featured: true,
    image: TYRE_BAY_SERVICE_IMAGES.fitting,
    description: 'Professional mount, balance, and old-tyre disposal for a full set of four wheels.',
    domain_data: { tyresize: '', rimsize: '', sourcing: 'local', loadindex: '', speedrating: '', runflat: 'No' },
  }),
  tyreProduct({
    name: 'Wheel Alignment (4 wheels)',
    brand: 'Tenvo Tyre Store',
    category: 'Services (Fitting)',
    sku: 'TT-SVC-ALIGN-4',
    price: 3500,
    unit: 'set',
    stock: 999,
    image: TYRE_BAY_SERVICE_IMAGES.alignment,
    description: 'Computerized four-wheel alignment for even wear and stable steering.',
    domain_data: { tyresize: '', rimsize: '', sourcing: 'local', loadindex: '', speedrating: '' },
  }),
  tyreProduct({
    name: 'Puncture Repair (single tyre)',
    brand: 'Tenvo Tyre Store',
    category: 'Services (Fitting)',
    sku: 'TT-SVC-PUNC-1',
    price: 800,
    unit: 'pcs',
    stock: 999,
    image: TYRE_BAY_SERVICE_IMAGES.puncture,
    description: 'Tubeless puncture repair with plug or patch as required.',
    domain_data: { tyresize: '', rimsize: '', sourcing: 'local', loadindex: '', speedrating: '' },
  }),
];

/**
 * @param {string} sku
 * @returns {Record<string, unknown> | undefined}
 */
export function getTyreSeedProductBySku(sku) {
  const key = String(sku || '').trim().toUpperCase();
  return TYRE_SEED_PRODUCTS.find((p) => String(p.sku || '').toUpperCase() === key);
}
