/**
 * Tenvo Water Supply Demo / water-delivery registration catalog.
 * PK home-delivery product mix inspired by market leaders (12L/19L refill,
 * dispensers, stands, PET cases, empty deposit). Imagery: Unsplash (Tenvo-branded).
 * Reference prices/workflow notes: lib/dataLab/waterShopArchiveExtract.json
 */
import { buildUnsplashImageUrl } from '../storefront/unsplashUrl.js';

/** Stable Unsplash photo ids (water bottles / dispensers / delivery). */
const P = {
  bottle19: '1548832330-d0f21f4b8f8b',
  bottleClear: '1564419320461-6870880221ad',
  glass: '1548832915-720091d6962b',
  dispenser: '1584622650111-993a426fbf0a',
  cooler: '1602143407151-7111542de6e8',
  delivery: '1600880292203-757bb62b4baf',
  petCase: '1622484212850-eb5969ee8b37',
  splash: '1523362627515-5dbf0d2d6c5a',
  kitchen: '1556911220-e15b29be8c8f',
  office: '1497366216548-37526070297c',
};

/** @param {string} photoId */
function img(photoId) {
  return buildUnsplashImageUrl(photoId, { w: 800, q: 82 });
}

export const WATER_SHOP_SEED_CATEGORIES = [
  '19L Dispenser',
  '12L / 6L Family',
  'Family Packs (1.5L)',
  'PET Small Bottles',
  'Water Dispensers / Stands',
  'Empty Bottle Deposit',
  'Office / Corporate',
  'Seasonal Bundles',
];

export const WATER_SHOP_MARKETING_HERO_IMAGE = img(P.bottle19);

/**
 * @param {object} partial
 * @returns {Record<string, unknown>}
 */
function waterProduct(partial) {
  const {
    name,
    brand = 'Tenvo Water',
    category,
    sku,
    price,
    compare_price,
    unit = 'bottle',
    stock = 120,
    featured = false,
    image,
    description,
    domain_data = {},
  } = partial;
  const cost = Math.round(Number(price) * 0.55);
  return {
    name,
    brand,
    category,
    unit,
    price,
    compare_price: compare_price ?? null,
    cost_price: cost,
    stock,
    sku,
    description:
      description ||
      `${name}. Mineral-enriched drinking water from Tenvo Water Supply. Home and office doorstep delivery across Pakistan.`,
    image_url: image,
    imageCredit: 'Unsplash seed',
    is_featured: featured,
    domain_data: {
      bottlesize: domain_data.bottlesize || '',
      refilltype: domain_data.refilltype || 'Refill (empty return)',
      productcode: domain_data.productcode || '',
      brand: brand,
      depositamount: domain_data.depositamount ?? 0,
      othercompany: domain_data.othercompany || 'No',
      packtype: domain_data.packtype || 'Single bottle',
      ...domain_data,
    },
  };
}

/** @type {Array<Record<string, unknown>>} */
export const WATER_SHOP_SEED_PRODUCTS = [
  waterProduct({
    name: '19L Mineral Water (Refill)',
    category: '19L Dispenser',
    sku: 'WTR-19L-REFILL-01',
    unit: 'bottle',
    price: 150,
    compare_price: 170,
    stock: 400,
    featured: true,
    image: img(P.bottle19),
    description:
      'Standard 19-litre dispenser refill. Rider delivers full bottles and collects empties (DEL / REC). Account rate available.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Refill (empty return)',
      productcode: '1',
      depositamount: 800,
      packtype: 'Single bottle',
    },
  }),
  waterProduct({
    name: '19L New Bottle + First Fill',
    category: '19L Dispenser',
    sku: 'WTR-19L-NEW-02',
    unit: 'bottle',
    price: 950,
    stock: 80,
    featured: true,
    image: img(P.bottleClear),
    description:
      'New 19L bottle with first fill. Security deposit applies on account (refundable on close).',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Both',
      productcode: '1N',
      depositamount: 800,
    },
  }),
  waterProduct({
    name: '12L Family Bottle (Refill)',
    category: '12L / 6L Family',
    sku: 'WTR-12L-REFILL-03',
    unit: 'bottle',
    price: 120,
    stock: 200,
    featured: true,
    image: img(P.bottleClear),
    description: '12-litre family pack refill for homes without a full 19L stand.',
    domain_data: {
      bottlesize: '12L',
      refilltype: 'Refill (empty return)',
      productcode: '12',
      depositamount: 500,
    },
  }),
  waterProduct({
    name: '6 Liters Bottle',
    category: '12L / 6L Family',
    sku: 'WTR-6L-04',
    unit: 'bottle',
    price: 80,
    stock: 180,
    featured: false,
    image: img(P.splash),
    description: '6L family bottle — easy lift for flats and kitchens.',
    domain_data: {
      bottlesize: '6L',
      refilltype: 'One-way sealed',
      productcode: '6',
    },
  }),
  waterProduct({
    name: '5L Sealed Jug',
    category: '12L / 6L Family',
    sku: 'WTR-5L-05',
    unit: 'bottle',
    price: 70,
    stock: 150,
    image: img(P.glass),
    description: '5L sealed jug for picnics, offices, and short trips.',
    domain_data: { bottlesize: '5L', refilltype: 'One-way sealed', productcode: '5' },
  }),
  waterProduct({
    name: '1.5L Sealed (Case of 12)',
    category: 'Family Packs (1.5L)',
    sku: 'WTR-15L-CASE12-06',
    unit: 'case',
    price: 720,
    stock: 90,
    featured: true,
    image: img(P.petCase),
    description: 'Case of 12 × 1.5L sealed bottles. Ideal for homes and events.',
    domain_data: {
      bottlesize: '1.5L',
      refilltype: 'One-way sealed',
      packtype: 'Case of 12',
      productcode: '15C',
    },
  }),
  waterProduct({
    name: '1.5L Single Bottle',
    category: 'Family Packs (1.5L)',
    sku: 'WTR-15L-SINGLE-07',
    unit: 'bottle',
    price: 70,
    stock: 300,
    image: img(P.petCase),
    description: 'Single 1.5L sealed bottle.',
    domain_data: { bottlesize: '1.5L', refilltype: 'One-way sealed', productcode: '15' },
  }),
  waterProduct({
    name: '500ml PET (Case of 24)',
    category: 'PET Small Bottles',
    sku: 'WTR-500-CASE24-08',
    unit: 'case',
    price: 480,
    stock: 70,
    featured: true,
    image: img(P.petCase),
    description: 'Case of 24 × 500ml PET — offices, gyms, and events.',
    domain_data: {
      bottlesize: '500ml',
      refilltype: 'One-way sealed',
      packtype: 'Case of 24',
      productcode: '500C',
    },
  }),
  waterProduct({
    name: '330ml PET (Case of 24)',
    category: 'PET Small Bottles',
    sku: 'WTR-330-CASE24-09',
    unit: 'case',
    price: 360,
    stock: 60,
    image: img(P.splash),
    description: 'Case of 24 × 330ml small PET.',
    domain_data: {
      bottlesize: '330ml',
      refilltype: 'One-way sealed',
      packtype: 'Case of 24',
      productcode: '330C',
    },
  }),
  waterProduct({
    name: '600ml Sports Bottle (Case of 24)',
    category: 'PET Small Bottles',
    sku: 'WTR-600-CASE24-10',
    unit: 'case',
    price: 520,
    stock: 50,
    image: img(P.glass),
    description: '600ml sports PET case for schools and gyms.',
    domain_data: {
      bottlesize: '600ml',
      refilltype: 'One-way sealed',
      packtype: 'Case of 24',
      productcode: '600C',
    },
  }),
  waterProduct({
    name: 'Cradle Tap Stand',
    category: 'Water Dispensers / Stands',
    sku: 'WTR-STAND-CRADLE-11',
    unit: 'pcs',
    price: 1000,
    stock: 40,
    featured: true,
    image: img(P.dispenser),
    description: 'Simple cradle tap-stand for 19L bottles. No power needed.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Both',
      packtype: 'Dispenser + stand',
      productcode: 'ST1',
    },
  }),
  waterProduct({
    name: 'Electronic Hot & Cold Dispenser',
    category: 'Water Dispensers / Stands',
    sku: 'WTR-DISP-ELEC-12',
    unit: 'pcs',
    price: 2000,
    stock: 25,
    featured: true,
    image: img(P.cooler),
    description: 'Hot and cold electronic dispenser for 19L bottles. Rider can install on first visit.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Both',
      packtype: 'Dispenser + stand',
      productcode: 'ST2',
    },
  }),
  waterProduct({
    name: 'Tabletop Dispenser',
    category: 'Water Dispensers / Stands',
    sku: 'WTR-DISP-TABLE-13',
    unit: 'pcs',
    price: 950,
    stock: 30,
    image: img(P.dispenser),
    description: 'Compact tabletop dispenser for flats and small offices.',
    domain_data: {
      bottlesize: '19L Dispenser',
      packtype: 'Dispenser + stand',
      productcode: 'ST3',
    },
  }),
  waterProduct({
    name: 'Premium Floor Dispenser',
    category: 'Water Dispensers / Stands',
    sku: 'WTR-DISP-PREM-14',
    unit: 'pcs',
    price: 27500,
    stock: 8,
    image: img(P.cooler),
    description: 'Premium floor-standing hot & cold dispenser for corporate lobbies.',
    domain_data: {
      bottlesize: '19L Dispenser',
      packtype: 'Dispenser + stand',
      productcode: 'ST4',
    },
  }),
  waterProduct({
    name: '19L Bottle Deposit (Security)',
    category: 'Empty Bottle Deposit',
    sku: 'WTR-DEP-19L-15',
    unit: 'pcs',
    price: 800,
    stock: 500,
    featured: false,
    image: img(P.bottle19),
    description:
      'Refundable security deposit per 19L bottle on account. Min 3 bottles for free home delivery routes.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Empty purchase (MT)',
      depositamount: 800,
      productcode: 'DEP',
    },
  }),
  waterProduct({
    name: 'Empty Bottle Purchase (MT)',
    category: 'Empty Bottle Deposit',
    sku: 'WTR-MT-EMPTY-16',
    unit: 'pcs',
    price: 50,
    stock: 200,
    image: img(P.bottleClear),
    description: 'Purchase of empty other-company bottles (MT) for plant reuse tracking.',
    domain_data: {
      refilltype: 'Empty purchase (MT)',
      othercompany: 'Yes',
      productcode: 'MT',
    },
  }),
  waterProduct({
    name: 'Office Weekly Pack (4×19L)',
    category: 'Office / Corporate',
    sku: 'WTR-OFF-4X19-17',
    unit: 'case',
    price: 600,
    stock: 100,
    featured: true,
    image: img(P.office),
    description: 'Corporate weekly pack — four 19L refills on a fixed delivery day.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Refill (empty return)',
      packtype: 'Case of 12',
      productcode: 'OFF4',
      depositamount: 3200,
    },
  }),
  waterProduct({
    name: 'Mosque / School Bulk (10×19L)',
    category: 'Office / Corporate',
    sku: 'WTR-BULK-10X19-18',
    unit: 'case',
    price: 1400,
    stock: 40,
    image: img(P.delivery),
    description: 'Bulk 10×19L refill for mosques, schools, and community halls.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Refill (empty return)',
      productcode: 'BLK10',
    },
  }),
  waterProduct({
    name: 'Summer Saviour Bundle (8×19L + Stand)',
    category: 'Seasonal Bundles',
    sku: 'WTR-BND-SUMMER-19',
    unit: 'set',
    price: 2200,
    compare_price: 2600,
    stock: 35,
    featured: true,
    image: img(P.kitchen),
    description:
      'Seasonal home starter: 8×19L refills plus cradle stand. Perfect for DHA, Clifton, and Bahria Town routes.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Both',
      packtype: 'Dispenser + stand',
      productcode: 'BND1',
    },
  }),
  waterProduct({
    name: 'Coupon Book 11×19L',
    category: 'Seasonal Bundles',
    sku: 'WTR-CPN-11X19-20',
    unit: 'pcs',
    price: 1650,
    compare_price: 1870,
    stock: 60,
    featured: true,
    image: img(P.bottle19),
    description:
      '11 coupons for 19L refills — prepaid book saves vs cash per bottle. Switch pay mode anytime.',
    domain_data: {
      bottlesize: '19L Dispenser',
      refilltype: 'Refill (empty return)',
      productcode: 'CPN11',
    },
  }),
];

export const WATER_SHOP_SEED_PRODUCT_COUNT = WATER_SHOP_SEED_PRODUCTS.length;

/** Demo route customers for hub hisab smoke (optional seed helpers). */
export const WATER_SHOP_DEMO_ROUTE_HINTS = [
  {
    name: 'Villa 303 — DHA Phase 6',
    domain_data: {
      customertype: 'Home & Flat',
      accountno: '55',
      towncode: '101',
      city: 'Karachi',
      deliveryarea: 'DHA Phase 6',
      postalcode: '75500',
      houseno: 'Villa 303',
      floorflat: 'Ground',
      deliverydays: 'Mon Wed Fri',
      dailybottles: 2,
      productrate: 150,
      bottlebalance: 2,
      deliveryactive: 'Yes',
      preferredpayment: 'Monthly Credit',
    },
  },
  {
    name: 'Flat 5F-11A — Clifton',
    domain_data: {
      customertype: 'Home & Flat',
      accountno: '1-101-356',
      towncode: '102',
      city: 'Karachi',
      deliveryarea: 'Clifton',
      postalcode: '75600',
      houseno: 'Block 5',
      floorflat: '5F 11A',
      deliverydays: 'Tue Thu Sat',
      dailybottles: 1,
      productrate: 150,
      bottlebalance: 1,
      deliveryactive: 'Yes',
      preferredpayment: 'Cash',
    },
  },
  {
    name: 'BTK Bahria Office',
    domain_data: {
      customertype: 'Corporate',
      accountno: 'CORP-88',
      towncode: '220',
      city: 'Karachi',
      deliveryarea: 'Bahria Town Karachi',
      postalcode: '75340',
      houseno: 'Plaza A-12',
      floorflat: '2nd floor',
      deliverydays: 'Weekdays',
      dailybottles: 4,
      productrate: 140,
      bottlebalance: 8,
      deliveryactive: 'Yes',
      preferredpayment: 'Weekly Credit',
    },
  },
];
