/**
 * Maps each business vertical (62 keys) to a brand-catalog category per market.
 * Categories align with keys in lib/regionalMarket/brandCatalogs/*.js
 */
export const DOMAIN_BRAND_CATEGORY = Object.freeze({
  'retail-shop': 'grocery',
  supermarket: 'grocery',
  grocery: 'grocery',
  fmcg: 'personalCare',
  pharmacy: 'pharmaceutical',
  'bakery-confectionery': 'bakery',
  garments: 'clothing',
  'boutique-fashion': 'designer',
  'leather-footwear': 'footwear',
  'textile-wholesale': 'textile',
  'textile-mill': 'textile',
  mobile: 'mobile',
  'electronics-goods': 'electronics',
  'computer-hardware': 'electronics',
  'mobile-repairing': 'mobile',
  ecommerce: 'general',
  'auto-parts': 'autoparts',
  'auto-workshop': 'autoparts',
  'tyre-shop': 'autoparts',
  'rent-a-car': 'autoparts',
  paint: 'paint',
  'construction-material': 'construction',
  'steel-iron': 'steel',
  'steel-industry': 'steel',
  'hardware-sanitary': 'construction',
  'ceramics-tiles': 'construction',
  electrical: 'electronics',
  furniture: 'general',
  'gems-jewellery': 'designer',
  'bookshop-stationery': 'general',
  'book-publishing': 'general',
  'restaurant-cafe': 'food',
  'hotel-guesthouse': 'food',
  travel: 'general',
  'event-management': 'general',
  'salon-spa': 'personalCare',
  'gym-fitness': 'personalCare',
  'dental-clinic': 'pharmaceutical',
  'veterinary-clinic': 'pharmaceutical',
  'diagnostic-lab': 'pharmaceutical',
  'clinics-healthcare': 'pharmaceutical',
  'school-education': 'general',
  'school-library': 'general',
  'wholesale-distribution': 'grocery',
  'cold-storage': 'food',
  'courier-logistics': 'general',
  'logistics-transport': 'general',
  'petrol-pump': 'general',
  'real-estate': 'general',
  'solar-energy': 'electronics',
  'industrial-parts': 'autoparts',
  'marine-parts': 'autoparts',
  chemical: 'general',
  'plastic-manufacturing': 'general',
  'printing-packaging': 'general',
  'paper-mill': 'general',
  'flour-mill': 'food',
  'rice-mill': 'food',
  'sugar-mill': 'food',
  agriculture: 'food',
  'dairy-farm': 'food',
  'poultry-farm': 'food',
  'livestock-cattle': 'food',
});

/** @param {string} domainKey */
export function getBrandCategoryForDomain(domainKey) {
  return DOMAIN_BRAND_CATEGORY[domainKey] || 'general';
}
